#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RLI.WebApplication;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SharedSvgs/_mInstructorLogo.cshtml")]
    public partial class _Views_SharedSvgs__mInstructorLogo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_SharedSvgs__mInstructorLogo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<?xml version=\"1.0\" encoding=\"utf-8\" ?>\r\n<!-- Generator: Adobe Illustrator 23.0.1" +
", SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->\r\n<svg");

WriteLiteral(" version=\"1.1\"");

WriteLiteral(" id=\"Warstwa_1\"");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" x=\"0px\"");

WriteLiteral(" y=\"0px\"");

WriteLiteral("\r\n     viewBox=\"0 0 26 31\"");

WriteLiteral(" style=\"enable-background:new 0 0 26 31;\"");

WriteLiteral(" xml:space=\"preserve\"");

WriteLiteral(">\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .st0 {\r\n        fill: #292656;\r\n    }\r\n\r\n    .st1 {\r\n        fill: #FFFFFF" +
";\r\n    }\r\n</style>\r\n<g>\r\n<path");

WriteLiteral(" class=\"st0\"");

WriteLiteral(" d=\"M21.8,24.5c0,0.9-0.8,1.7-1.7,1.7H6.7c-0.9,0-1.7-0.8-1.7-1.7V11.1c0-0.9,0.8-1." +
"7,1.7-1.7h13.4\r\n\t\tc0.9,0,1.7,0.8,1.7,1.7V24.5z\"");

WriteLiteral(" />\r\n</g>\r\n<g>\r\n<path");

WriteLiteral(" class=\"st1\"");

WriteLiteral(@" d=""M16.4,21.5v2.4c0,0.4-0.1,0.7-0.2,0.8C16,24.9,15.8,25,15.5,25s-0.5-0.1-0.7-0.3c-0.2-0.2-0.2-0.5-0.2-0.8
		v-2.8c0-0.5,0-0.8,0-1c0-0.2-0.1-0.5-0.2-0.6c-0.1-0.2-0.3-0.2-0.6-0.2c-0.6,0-1,0.2-1.1,0.6c-0.2,0.4-0.3,1-0.3,1.7v2.4
		c0,0.4-0.1,0.7-0.2,0.8c-0.2,0.2-0.4,0.3-0.7,0.3c-0.3,0-0.5-0.1-0.7-0.3c-0.2-0.2-0.2-0.5-0.2-0.8v-5c0-0.3,0.1-0.6,0.2-0.8
		c0.1-0.2,0.3-0.2,0.6-0.2c0.2,0,0.5,0.1,0.6,0.2c0.2,0.2,0.2,0.4,0.2,0.7v0.2c0.3-0.4,0.6-0.6,1-0.8c0.3-0.2,0.7-0.2,1.2-0.2
		s0.8,0.1,1.1,0.3c0.3,0.2,0.6,0.5,0.8,0.8c0.3-0.3,0.6-0.6,1-0.8c0.3-0.2,0.7-0.3,1.1-0.3c0.5,0,0.9,0.1,1.3,0.3
		c0.3,0.2,0.6,0.5,0.8,0.8c0.1,0.3,0.2,0.8,0.2,1.5v3.5c0,0.4-0.1,0.7-0.2,0.8c-0.2,0.2-0.4,0.3-0.7,0.3s-0.5-0.1-0.7-0.3
		c-0.2-0.2-0.2-0.5-0.2-0.8v-3c0-0.4,0-0.7,0-0.9c0-0.2-0.1-0.4-0.3-0.6c-0.2-0.2-0.3-0.2-0.7-0.2c-0.2,0-0.5,0.1-0.7,0.2
		s-0.4,0.3-0.5,0.6C16.5,20.2,16.4,20.7,16.4,21.5z""");

WriteLiteral(" />\r\n</g>\r\n</svg>\r\n");

        }
    }
}
#pragma warning restore 1591
