#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RLI.WebApplication;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SharedSvgs/_SynchronousLearningIcon.cshtml")]
    public partial class _Views_SharedSvgs__SynchronousLearningIcon_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_SharedSvgs__SynchronousLearningIcon_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<svg");

WriteLiteral(" id=\"Layer_Assignment\"");

WriteLiteral(" data-name=\"Layer 1\"");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" viewBox=\"0 0 100 100\"");

WriteLiteral(@">
    <defs>
        <style>
            .assignment-1 {
                fill: #1a133b;
            }

            .assignment-2 {
                fill: #f97735;
            }

            .assignment-3 {
                fill: #d86430;
            }

            .assignment-4 {
                fill: #fdad9b;
            }

            .assignment-5 {
                fill: #fdd194;
            }

            .assignment-6 {
                fill: #b0db43;
            }

            .assignment-7 {
                fill: #7fb069;
            }

            .assignment-8 {
                fill: #edf1f4;
            }

            .assignment-9 {
                fill: #aec2b8;
            }
        </style>
    </defs>
    <path");

WriteLiteral(" class=\"assignment-1\"");

WriteLiteral(@" d=""M95.74,49.86a47.63,47.63,0,0,1-29,44,1.68,1.68,0,0,1-1.17.05,58.76,58.76,0,0,0-35,0,1.69,1.69,0,0,1-1.15,0A47.81,47.81,0,0,1,11.4,80.32a1.25,1.25,0,0,1,.09-1.68A47.47,47.47,0,0,0,25.57,44.69a47.46,47.46,0,0,0-9.18-28,1.79,1.79,0,0,1,.28-2.4A47.61,47.61,0,0,1,95.74,49.86Z""");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-2\"");

WriteLiteral(" d=\"M29.46,74.1H66.78V93.82a47.72,47.72,0,0,1-37.32,0Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-3\"");

WriteLiteral(" d=\"M35.49,89v6.94a47.74,47.74,0,0,1-6-2.1V74.1H66.78v11H39.37A3.89,3.89,0,0,0,35" +
".49,89Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-2\"");

WriteLiteral(" d=\"M95.88,20.07V74.49a5.83,5.83,0,0,1-5.83,5.83H11.54a47.61,47.61,0,0,1,5.28-66." +
"08H90.05A5.83,5.83,0,0,1,95.88,20.07Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-4\"");

WriteLiteral(" d=\"M45,46.89A19.44,19.44,0,1,1,25.57,27.45,19.44,19.44,0,0,1,45,46.89Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-5\"");

WriteLiteral(" d=\"M77.75,87.44a37.33,37.33,0,0,1-5.26,3.61L50.2,65.68l11.3-7.91Zm-59,0A35.38,35" +
".38,0,0,0,24,91.05L46.3,65.68,35,57.77Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-6\"");

WriteLiteral(" d=\"M96.5,77.47a3.1,3.1,0,0,1-3.22,3H9.08a3,3,0,1,1,0-6h84.2A3.11,3.11,0,0,1,96.5" +
",77.47Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-7\"");

WriteLiteral(" d=\"M56.74,77.64a2.86,2.86,0,0,1-2.91,2.81H11.6A46.59,46.59,0,0,1,8,74.82H53.83A2" +
".86,2.86,0,0,1,56.74,77.64Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-8\"");

WriteLiteral(" d=\"M89.71,74.61H39.18a2,2,0,0,1-2-2V22.35a2,2,0,0,1,2-2H89.71a2,2,0,0,1,2,2v50.3" +
"A2,2,0,0,1,89.71,74.61Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-1\"");

WriteLiteral(" d=\"M83.88,34.26V36.2a1,1,0,0,1-1,1H50.84a1,1,0,0,1-1-1V34.26a1,1,0,0,1,1-1H82.91" +
"A1,1,0,0,1,83.88,34.26ZM80,41.06H53.76a1,1,0,0,0-1,1V44a1,1,0,0,0,1,1H80a1,1,0,0" +
",0,1-1V42A1,1,0,0,0,80,41.06Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-8\"");

WriteLiteral(" d=\"M40.91,22.35v50.3a2,2,0,0,1-1.94,2H7a48.48,48.48,0,0,1,3.78-54.22H39A2,2,0,0," +
"1,40.91,22.35Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-9\"");

WriteLiteral(" d=\"M33.42,72V74a1.09,1.09,0,0,1-1.18,1H13.32a1.1,1.1,0,0,1-1.18-1V72a.75.75,0,0," +
"1,1.18-.63H32.24A.75.75,0,0,1,33.42,72Z\"");

WriteLiteral(" />\r\n    <path");

WriteLiteral(" class=\"assignment-1\"");

WriteLiteral(@" d=""M75.14,55.64v3.88a1,1,0,0,1-1,1H59.59a1,1,0,0,1-1-1V55.64a1,1,0,0,1,1-1H74.16A1,1,0,0,1,75.14,55.64Zm-51-9.42L38.38,40a1,1,0,0,0,0-1.79L24.1,32A3.89,3.89,0,0,0,21,32L6.72,38.22a1,1,0,0,0,0,1.79L21,46.22A3.89,3.89,0,0,0,24.1,46.22Zm7.8.75-7.15,2.91a5.78,5.78,0,0,1-4.4,0L13.2,47a1,1,0,0,0-1.34.9V59.52a1,1,0,0,0,1,1H32.27a1,1,0,0,0,1-1V47.87A1,1,0,0,0,31.9,47Zm7,6V44.49a1,1,0,0,0-1.91,0L37,53c-1.14.66-2,2.47-2,4.59h5.83C40.82,55.47,40,53.67,38.88,53Z""");

WriteLiteral(" />\r\n</svg>");

        }
    }
}
#pragma warning restore 1591
