#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Messages/_Conversation.cshtml")]
    public partial class _Views_Messages__Conversation_cshtml : System.Web.Mvc.WebViewPage<RLI.Common.DataObjects.ConversationMessagesModel>
    {
        public _Views_Messages__Conversation_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(" id=\"m_section_\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"m_quick_sidebar_tabs_messenger\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"m-messenger m-messenger--message-arrow m-messenger--skin-light\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"loader\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"messenger_messages_container\"");

WriteLiteral(" class=\"m-messenger__messages messenger_messages_container\"");

WriteLiteral(" style=\"max-height:500px;overflow-y:scroll;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 8 "..\..\Views\Messages\_Conversation.cshtml"
           Write(Html.Partial("_Messages", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"m-messenger__seperator\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"m-messenger__form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"m-messenger__form-controls\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"messenger_text_input\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"\"");

WriteLiteral(" placeholder=\"Type here...\"");

WriteLiteral(" class=\"m-messenger__form-input messenger_text_input\"");

WriteLiteral(" data-user_id=\"\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"m-messenger__form-tools\"");

WriteLiteral(">\r\n\r\n                    <a");

WriteLiteral(" id=\"messenger_send_message\"");

WriteLiteral(" class=\"m-messenger__form-attachment messenger_send_message btn-primary\"");

WriteLiteral(" data-user_id=\"");

            
            #line 17 "..\..\Views\Messages\_Conversation.cshtml"
                                                                                                                                    Write(ViewBag.to_userId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-conv_id=\"");

            
            #line 17 "..\..\Views\Messages\_Conversation.cshtml"
                                                                                                                                                                      Write(Model.id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" style=\"margin-bottom:30px\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"la la-send\"");

WriteLiteral("></i>\r\n                    </a>\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
