#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PresentialSessionsTable.cshtml")]
    public partial class _Views_Shared__PresentialSessionsTable_cshtml : System.Web.Mvc.WebViewPage<List<RLI.WebApplication.Models.PresentialSessionsDetails>>
    {
        public _Views_Shared__PresentialSessionsTable_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;
    ViewBag.Title = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageSyPresentialSessionsIndex"));

    Language currentLanguage = ViewBag.CurrentLanguage;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<table");

WriteLiteral(" class=\"table table-striped- table-bordered table-hover table-checkable mt-5\"");

WriteLiteral(" id=\"m_table_1\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>\r\n            </th>\r\n            <t" +
"h>\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadGrade")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadSubject")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadChapter")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 27 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadTopic")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 30 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadTeacher")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadTitle")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "PresentialSessionsPageTableHeadSessionDate")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n\r\n            </th>\r\n        </tr>\r\n    </" +
"thead>\r\n    <tbody>\r\n");

            
            #line 44 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 48 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.PresentialSessionKey);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.Grade);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.Subject);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 57 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.Chapter);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.Topic);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 64 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.Teacher);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 67 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 70 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
               Write(item.SessionDate);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n                </td>\r\n           " +
" </tr>\r\n");

            
            #line 75 "..\..\Views\Shared\_PresentialSessionsTable.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
