#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/StudentsSubmissionPage/_StudentSubmissionCard.cshtml")]
    public partial class _Views_StudentsSubmissionPage__StudentSubmissionCard_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<RLI.Common.DataObjects.GetAssignmentSubmissionsResultModel>>
    {
        public _Views_StudentsSubmissionPage__StudentSubmissionCard_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
  
    int i = -1;
    int gradedIndex = -1;
    int notGradedIndex = -1;
    int draftdIndex = -1;
    int notViewedIndex = -1;


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
 foreach (var sub in Model)
{
    bool isGraded = false;
    int index = -1;
    //if(sub.MoodleGradeScore != "" && sub.MoodleGradeScore != null)
    //{
    //    isGraded = true;

    //}
    if (sub.GradingStatus == "graded" && sub.Status == "submitted")
    {
        isGraded = true;
        index = ++gradedIndex;
    }
    if (sub.GradingStatus == "notgraded" && sub.Status == "submitted")
    {
        index = ++notGradedIndex;
    }
    if (sub.Status == "new" || sub.Status == "draft")
    {
        index = ++draftdIndex;
    }
    if (sub.Status == "notviewed")
    {
        index = ++notViewedIndex;
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"m-widget4 grid effect-2 studentSubmissionsGrid col-lg-4 col-md-4\"");

WriteLiteral(" data-graded =\"");

            
            #line 39 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                           Write(isGraded);

            
            #line default
            #line hidden
WriteLiteral("\" data-index=\"");

            
            #line 39 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                  Write(index);

            
            #line default
            #line hidden
WriteLiteral("\" data-userId=\"");

            
            #line 39 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                                       Write(sub.UserId);

            
            #line default
            #line hidden
WriteLiteral("\" data-assigId=\"");

            
            #line 39 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                                                                  Write(sub.AssignmentId);

            
            #line default
            #line hidden
WriteLiteral("\" data-status=\"");

            
            #line 39 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                                                                                                  Write(sub.Status);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"not a button\" style=\"-webkit-perspective:1px;perspective:1px;cursor:not-" +
"allowed;\">\r\n        <div");

WriteLiteral(" class=\"m-widget4__item  studentSubmissionCard mb-5 p-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"m-widget4__img m-widget4__img--pic\"");

WriteLiteral(" style=\"color: #2b2350 !important;\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-2x fa-user-graduate\"");

WriteLiteral("></i>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                          Write(sub.FullName);

            
            #line default
            #line hidden
WriteLiteral("</span><br>\r\n                <span");

WriteLiteral(" class=\"m-widget4__sub\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                        Write(sub.Grade);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n");

            
            #line 49 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
             if (isGraded)
            {
                double grade = Double.Parse(sub.MoodleGradeScore);
                if (grade < 50)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1920), Tuple.Create("\"", 1992)
            
            #line 55 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
, Tuple.Create(Tuple.Create("", 1927), Tuple.Create<System.Object, System.Int32>(Url.Action("StudentSubmissionDetails", "StudentsSubmissionPage")
            
            #line default
            #line hidden
, 1927), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn m-btn--pill btn-sm btn-danger\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                                                         Write(grade);

            
            #line default
            #line hidden
WriteLiteral(" %</a>\r\n                    </div>\r\n");

            
            #line 57 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                }
                else if (grade > 50)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2246), Tuple.Create("\"", 2318)
            
            #line 61 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
, Tuple.Create(Tuple.Create("", 2253), Tuple.Create<System.Object, System.Int32>(Url.Action("StudentSubmissionDetails", "StudentsSubmissionPage")
            
            #line default
            #line hidden
, 2253), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn m-btn--pill btn-sm btn-success\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                                                          Write(grade);

            
            #line default
            #line hidden
WriteLiteral(" %</a>\r\n                    </div>\r\n");

            
            #line 63 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2557), Tuple.Create("\"", 2629)
            
            #line 67 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
, Tuple.Create(Tuple.Create("", 2564), Tuple.Create<System.Object, System.Int32>(Url.Action("StudentSubmissionDetails", "StudentsSubmissionPage")
            
            #line default
            #line hidden
, 2564), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn m-btn--pill btn-sm btn-brand\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                                                                                                                                                        Write(grade);

            
            #line default
            #line hidden
WriteLiteral(" %</a>\r\n                    </div> \r\n");

            
            #line 69 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
                }

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 74 "..\..\Views\StudentsSubmissionPage\_StudentSubmissionCard.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
