#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 5 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
    using System.Web.Http;
    
    #line default
    #line hidden
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 6 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
    using RLI.Common.DataObjects;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/StudentsSubmissionPage/_SubmissionDetails.cshtml")]
    public partial class _Views_StudentsSubmissionPage__SubmissionDetails_cshtml : System.Web.Mvc.WebViewPage<RLI.Common.DataObjects.SubmissionDetailsViewModel>
    {
        public _Views_StudentsSubmissionPage__SubmissionDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
  
    string stringNextFullName = ViewBag.nextFullName;
    Dictionary<string, string> Locale = ViewBag.Locale;
    ViewBag.Title = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsDetails"));


            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 14 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
  
    var maxScore = 100; // Set your max score here
    var totalScore = ViewBag.TotalScore != null ? ViewBag.TotalScore : 0; // Default to 0 if null
    var progressPercentage = (totalScore * 100) / maxScore; // Calculate percentage

    bool iscoordinator = false;

    if ((User.IsInRole("ContentManager") || User.IsInRole("Coordinator") || User.IsInRole("HeadOfDepartment") || User.IsInRole("SchoolDirector") || User.IsInRole("SchoolPrincipal") || User.IsInRole("SeniorCoordinator")) || ViewBag.CurrentUser.Id != User.Identity.GetUserId())
    {

   // if (User.IsInRole("ContentManager") && ViewBag.CurrentUser.Id != User.Identity.GetUserId())
   // {
        iscoordinator = true;
    }

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    .m-widget4 .m-widget4__item {
        padding-bottom: 1rem !important;
    }

    .borderedWidgets {
        padding: 10px;
        border-radius: 15px;
    }

        .borderedWidgets .m-widget24__item .m-widget24__title {
            color: #fff !important;
        }

        .borderedWidgets .m-widget24__item .m-widget24__desc {
            color: #fff !important;
        }


    .lessonCard {
        width: 80% !important;
    }
</style>


<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"page-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"m-subheader\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"d-flex align-items-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"mr-auto\"");

WriteLiteral(">\r\n                            <h3");

WriteLiteral(" class=\"m-subheader__title \"");

WriteLiteral(">");

            
            #line 62 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageAutoCorrected")));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                        </div>\r\n                    </div>\r\n              " +
"  </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"mt-4 p-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-12 col-lg-8 col-xl-8\"");

WriteLiteral(" style=\"background:#923c7a;border-radius:15px;\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12 col-lg-8 col-xl-8 borderedWidgets\"");

WriteLiteral(" style=\"background: linear-gradient( 90deg, rgb(41 38 86) 0%, rgb(79 46 99) 50%, " +
"rgb(147 60 122) 100%);\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget24\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-widget24__item\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"far fa-calendar fa-2x\"");

WriteLiteral("> </i>\r\n                                                </span><br />\r\n          " +
"                                      <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 80 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageDueDate")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </span><br />\r\n                " +
"                                <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 83 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Model.DueDate);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </h4>\r\n                        " +
"                    </div>\r\n                                        </div>\r\n    " +
"                                </div>\r\n                                    <div" +
"");

WriteLiteral(" class=\"col-md-12 col-lg-4 col-xl-4 borderedWidgets\"");

WriteLiteral(" style=\"background:rgb(43 35 80);\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget24\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-widget24__item\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"far fa-calendar-plus fa-2x\"");

WriteLiteral("> </i>\r\n                                                </span><br />\r\n          " +
"                                      <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 95 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageExtensionDate")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </span><br />\r\n");

            
            #line 97 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                 if (Model.ExtensionDueDate != null)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 100 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                   Write(Model.ExtensionDueDate);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </h4>\r\n");

            
            #line 102 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n                                                        Not Available\r\n       " +
"                                             </h4>\r\n");

            
            #line 108 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral(@"

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div");

WriteLiteral(" class=\"col-md-12 col-lg-4 col-xl-4 m--margin-10-mobile\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12 col-lg-12 col-xl-12 borderedWidgets\"");

WriteLiteral(" style=\"background:linear-gradient( 90deg, rgba(249,120,53,1) 0%, rgba(252,152,64" +
",1) 50%, rgba(255,188,76,1) 100%)\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"m-widget24\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget24__item\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n                                                <i");

WriteLiteral(" class=\"far fa-clock fa-2x\"");

WriteLiteral("> </i>\r\n                                            </span><br />\r\n              " +
"                              <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 124 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageTimeRemaining")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span><br />\r\n");

            
            #line 126 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 126 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                              
                                                var timeRemaining = Model.TimeRemaining.Value;
                                                var timeRemainingHours = timeRemaining.Hours;
                                                var timeRemainingMinutes = timeRemaining.Minutes;
                                            
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 131 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 131 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                             if (timeRemainingHours != 0 && timeRemainingMinutes != 0)
                                            {
                                                if (timeRemainingHours == 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 136 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                   Write(timeRemainingMinutes);

            
            #line default
            #line hidden
WriteLiteral(" m ");

WriteLiteral("\r\n                                                    </h4>\r\n");

            
            #line 138 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 142 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                   Write(timeRemainingHours);

            
            #line default
            #line hidden
WriteLiteral(" h ");

            
            #line 142 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                         Write(timeRemainingMinutes);

            
            #line default
            #line hidden
WriteLiteral(" m ");

WriteLiteral("\r\n                                                    </h4>\r\n");

            
            #line 144 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                }
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <h4");

WriteLiteral(" class=\"m-widget24__title mt-0 m--font-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 149 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_DueDateSubmissionMessage")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </h4>\r\n");

            
            #line 151 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>

                <div");

WriteLiteral(" class=\"m-portlet mt-4 p-3\"");

WriteLiteral(" style=\"background:#f3f3ff;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-12 col-lg-8 col-xl-8\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12 col-lg-8 col-xl-8\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget24\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-widget24__item\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 172 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageLastModified")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </span><br>\r\n                  " +
"                              <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 175 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Model.LastModified);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </h4>\r\n\r\n                      " +
"                          <div");

WriteLiteral(" class=\"m--space-10\"");

WriteLiteral("></div>\r\n                                            </div>\r\n                    " +
"                    </div>\r\n                                    </div>\r\n        " +
"                            <div");

WriteLiteral(" class=\"col-md-12 col-lg-4 col-xl-4\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget24\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-widget24__item\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 186 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGradingStatus")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </span><br>\r\n");

            
            #line 188 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                 if (Model.GradingStatus == "graded")
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <h4");

WriteLiteral(" class=\"m-widget24__title mt-0 m--font-success\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 191 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                   Write(Model.GradingStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </h4>\r\n");

            
            #line 193 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <h4");

WriteLiteral(" class=\"m-widget24__title mt-0 m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 197 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                   Write(Model.GradingStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </h4>\r\n");

            
            #line 199 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"m--space-10\"");

WriteLiteral(@"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div");

WriteLiteral(" class=\"col-md-12 col-lg-4 col-xl-4\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12 col-lg-12 col-xl-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"m-widget24\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget24__item\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget24__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 211 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrade")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span>\r\n                          " +
"                  <br>\r\n");

            
            #line 214 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 214 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                             if (Model.Grade != "" && Model.Grade != null)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 217 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Raw(Model.Grade));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </h4>\r\n");

            
            #line 219 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <h4");

WriteLiteral(" class=\"m-widget24__title mt-0\"");

WriteLiteral(">\r\n                                                    0/100\r\n                   " +
"                             </h4>\r\n");

            
            #line 225 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"m--space-10\"");

WriteLiteral(@"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>


");

            
            #line 237 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                
            
            #line default
            #line hidden
            
            #line 237 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                 if (Model.scormPagesInfo != null)
                {
                    if (Model.scormPagesInfo.Count != 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-xl-5\"");

WriteLiteral(">\r\n                                <div>\r\n                                    <di" +
"v");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n                                        ");

WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"m-portlet mt-4\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"m-widget14\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"row  align-items-center\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"mt-3 col-12 p-0\"");

WriteLiteral(" id=\"autoCorrectContainer\"");

WriteLiteral(">\r\n                                                            ");

WriteLiteral(@"
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div");

WriteLiteral(" class=\"m-portlet mt-4\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"m-widget14\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"m-widget14__header\"");

WriteLiteral(">\r\n                                                        <h3");

WriteLiteral(" class=\"m-widget14__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");

            
            #line 288 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrade")));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 288 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                           Write(Model.ScormOverallGrade);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        </h3>\r\n                " +
"                                        <span");

WriteLiteral(" class=\"m-widget14__desc\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");

            
            #line 291 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageThisGradeisautomatic")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        </span>\r\n              " +
"                                      </div>\r\n                                  " +
"                  <div");

WriteLiteral(" class=\"row  align-items-center\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" id=\"chartdiv\"");

WriteLiteral(@"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--begin:: Widgets/Profit Share-->


");

            
            #line 303 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 303 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                          
                                            List<QualitativeFeedback_Result> qualitativeFeedback_Result = (List<QualitativeFeedback_Result>)ViewBag.qualitativeFeedback_Result;
                                        
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 307 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 307 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                         if (qualitativeFeedback_Result != null && qualitativeFeedback_Result.Count != 0)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 311 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                               Write(Html.Partial("_AutoCorrectedQualitativeCard", qualitativeFeedback_Result));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </div>\r\n                       " +
"                     </div>\r\n");

            
            #line 314 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                </div" +
">\r\n                                <!--end:: Widgets/Profit Share-->\r\n          " +
"                  </div>\r\n                            <div");

WriteLiteral(" class=\"col-xl-7\"");

WriteLiteral(">\r\n");

            
            #line 320 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 320 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                 if (Model.scormPagesInfo != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <!--begin:: Widgets/User Progress -->\r\n");

WriteLiteral("                                    <div");

WriteLiteral(" class=\"m-portlet m-portlet--full-height mt-4\"");

WriteLiteral(">\r\n\r\n                                        <div");

WriteLiteral(" class=\"m-portlet__body h-100\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"m_widget4_tab1_content\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"m-widget4 m-widget4--progress\"");

WriteLiteral(">\r\n");

            
            #line 329 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                        
            
            #line default
            #line hidden
            
            #line 329 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                         foreach (var scormInfo in Model.scormPagesInfo)
                                                        {

            
            #line default
            #line hidden
WriteLiteral("                                                            <div");

WriteLiteral(" class=\"m-widget4__item w-100\"");

WriteLiteral(">\r\n\r\n                                                                <div");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                                                    <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                        ");

            
            #line 335 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                   Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPagePage")));

            
            #line default
            #line hidden
WriteLiteral(" #");

            
            #line 335 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                                       Write(scormInfo.PageNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                                    </span>\r\n  " +
"                                                                  <br />\r\n      " +
"                                                              <span");

WriteLiteral(" class=\"m-widget4__title m--font-bold m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                        ");

            
            #line 339 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                    Write(scormInfo.PageTitle != null ? scormInfo.PageTitle : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                                    </span>\r\n  " +
"                                                                  <br />\r\n      " +
"                                                              <div");

WriteLiteral(" class=\"row mt-3\"");

WriteLiteral(">\r\n                                                                        <div");

WriteLiteral(" class=\"col-md-6 col-12\"");

WriteLiteral(">\r\n                                                                            <s" +
"pan");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                                ");

            
            #line 345 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageMistakeError")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                                            </s" +
"pan>\r\n                                                                          " +
"  <br />\r\n                                                                      " +
"      <span");

WriteLiteral(" class=\"m--font-danger ml-5\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                                ");

            
            #line 349 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                           Write(scormInfo.MistakeCount);

            
            #line default
            #line hidden
WriteLiteral(" / ");

            
            #line 349 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                     Write(scormInfo.ErrorCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                                            </s" +
"pan>\r\n                                                                        </" +
"div>\r\n                                                                        <d" +
"iv");

WriteLiteral(" class=\"col-md-6 col-12\"");

WriteLiteral(">\r\n                                                                            <s" +
"pan");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                                ");

            
            #line 354 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageCheck")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                                            </s" +
"pan>\r\n                                                                          " +
"  <br />\r\n                                                                      " +
"      <span");

WriteLiteral(" class=\"m--font-accent ml-5\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                                ");

            
            #line 358 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                           Write(scormInfo.CheckCount);

            
            #line default
            #line hidden
WriteLiteral(@"
                                                                            </span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div");

WriteLiteral(" class=\"m-widget4__progress\"");

WriteLiteral(">\r\n                                                                    <div");

WriteLiteral(" class=\"m-widget4__progress-wrapper\"");

WriteLiteral(">\r\n                                                                        <span");

WriteLiteral(" class=\"m-widget17__progress-number\"");

WriteLiteral(">");

            
            #line 365 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                             Write(scormInfo.PageGrade);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n                                                                      " +
"  <div");

WriteLiteral(" class=\"m-section__content\"");

WriteLiteral(">\r\n                                                                            <d" +
"iv");

WriteLiteral(" class=\"progress m-progress--sm\"");

WriteLiteral(">\r\n                                                                              " +
"  <div");

WriteLiteral(" class=\"progress-bar bg-brand\"");

WriteLiteral(" role=\"progressbar\"");

WriteAttribute("style", Tuple.Create(" style=\"", 23794), Tuple.Create("\"", 23830)
, Tuple.Create(Tuple.Create("", 23802), Tuple.Create("width:", 23802), true)
            
            #line 369 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                  , Tuple.Create(Tuple.Create(" ", 23808), Tuple.Create<System.Object, System.Int32>(scormInfo.PageGrade
            
            #line default
            #line hidden
, 23809), false)
, Tuple.Create(Tuple.Create("", 23829), Tuple.Create(";", 23829), true)
);

WriteLiteral(" aria-valuenow=\"25\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteAttribute("aria-valuemax", Tuple.Create(" aria-valuemax=\"", 23868), Tuple.Create("\"", 23904)
            
            #line 369 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                              , Tuple.Create(Tuple.Create("", 23884), Tuple.Create<System.Object, System.Int32>(scormInfo.PageGrade
            
            #line default
            #line hidden
, 23884), false)
);

WriteLiteral(@"></div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>
");

            
            #line 376 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                        }

            
            #line default
            #line hidden
WriteLiteral("                                                        <div");

WriteLiteral(" class=\"m-widget4__item w-100\"");

WriteLiteral(" style=\"height:125px;\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                                                <br />\r\n      " +
"                                                          <span");

WriteLiteral(" class=\"m-widget4__title m--font-danger\"");

WriteLiteral(@">
                                                                    Total
                                                                </span>
                                                            </div>
                                                            <div");

WriteLiteral(" class=\"m-widget4__progress\"");

WriteLiteral(">\r\n                                                                <div");

WriteLiteral(" class=\"m-widget4__progress-wrapper\"");

WriteLiteral(">\r\n                                                                    <span");

WriteLiteral(" class=\"m-widget17__progress-number\"");

WriteLiteral(">");

            
            #line 386 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                         Write(totalScore);

            
            #line default
            #line hidden
WriteLiteral("%</span>\r\n\r\n                                                                    <" +
"div");

WriteLiteral(" class=\"m-section__content\"");

WriteLiteral(">\r\n                                                                        <div");

WriteLiteral(" class=\"progress m-progress--sm\"");

WriteLiteral(">\r\n                                                                            <d" +
"iv");

WriteLiteral(" class=\"progress-bar bg-brand\"");

WriteLiteral(" role=\"progressbar\"");

WriteAttribute("style", Tuple.Create("\r\n                                                                               " +
"  style=\"", 25638), Tuple.Create("\"", 25756)
, Tuple.Create(Tuple.Create("", 25728), Tuple.Create("width:", 25728), true)
            
            #line 391 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
             , Tuple.Create(Tuple.Create(" ", 25734), Tuple.Create<System.Object, System.Int32>(progressPercentage
            
            #line default
            #line hidden
, 25735), false)
, Tuple.Create(Tuple.Create("", 25754), Tuple.Create("%;", 25754), true)
);

WriteAttribute("aria-valuenow", Tuple.Create(" aria-valuenow=\"", 25757), Tuple.Create("\"", 25784)
            
            #line 391 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                    , Tuple.Create(Tuple.Create("", 25773), Tuple.Create<System.Object, System.Int32>(totalScore
            
            #line default
            #line hidden
, 25773), false)
);

WriteLiteral("\r\n                                                                               " +
"  aria-valuemin=\"0\"");

WriteAttribute("aria-valuemax", Tuple.Create(" aria-valuemax=\"", 25885), Tuple.Create("\"", 25910)
            
            #line 392 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                 , Tuple.Create(Tuple.Create("", 25901), Tuple.Create<System.Object, System.Int32>(maxScore
            
            #line default
            #line hidden
, 25901), false)
);

WriteLiteral(@"></div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>



                                                        ");

WriteLiteral(@"

                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
");

            
            #line 471 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"




            
            #line default
            #line hidden
WriteLiteral("                                    <!--end:: Widgets/User Progress -->\r\n");

            
            #line 475 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                }
                                else
                                {
                                    
            
            #line default
            #line hidden
            
            #line 478 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                               Write(Html.Partial("_EmptySlateContainer", new ViewDataDictionary {
                                                                                                                                          { "title", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_EmptySlateTitle")).ToString() },
                                                                                                                                          { "subTitle",Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_InProgress")).ToString() }
                                                                                                                                          , { "description", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_ResultSoon")).ToString() }
                                                                                                                                          , { "action", false },
                                                                                                                                          { "actionBtnId", "" },
                                                                                                                                          { "actionBtnText", "" } }));

            
            #line default
            #line hidden
            
            #line 484 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                                                    
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 489 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"m-subheader\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"d-flex align-items-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"mr-auto\"");

WriteLiteral(">\r\n                            <h3");

WriteLiteral(" class=\"m-subheader__title \"");

WriteLiteral(">");

            
            #line 494 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageSubmissionComments")));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                        </div>\r\n                    </div>\r\n              " +
"  </div>\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"allCommentsLogContainer\"");

WriteLiteral(">\r\n");

            
            #line 500 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 500 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                      
                        int userId = int.Parse(ViewBag.userId);
                        var groupedBYCommentsTeacher = Model.getCommentResultModel.comments.Where(c => c.userid != userId).GroupBy(item => item.fullname).Select(group => new { Customer = group.Key, Items = group.ToList() }).ToList();
                        var groupedBYCommentsStudent = Model.getCommentResultModel.comments.Where(c => c.userid == userId).GroupBy(item => item.fullname).Select(group => new { Customer = group.Key, Items = group.ToList() }).ToList();
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 506 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 506 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                     foreach (var content in Model.getCommentResultModel.comments.OrderBy(c => c.timecreated))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"col-12 m-3\"");

WriteLiteral(">\r\n");

            
            #line 509 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 509 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                             if (content.userid != userId)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <h4");

WriteLiteral(" class=\"m--font-brand\"");

WriteLiteral(">");

            
            #line 511 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                     Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageYou")));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

            
            #line 512 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <h4");

WriteLiteral(" class=\"m--font-accent\"");

WriteLiteral(">");

            
            #line 515 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                      Write(content.fullname);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

            
            #line 516 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 518 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                       Write(Html.Raw(content.content));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <p>\r\n");

WriteLiteral("                                ");

            
            #line 520 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                           Write(RLI.Common.Managers.UtilitiesManager.ConvertFromUnixTimestamp(content.timecreated));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 522 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 522 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                 if (content.userid != userId)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-CommentId=\"");

            
            #line 524 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                          Write(content.id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"m-5 deleteComment\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral("></i></a>\r\n");

            
            #line 525 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </p>\r\n\r\n                        </div>\r\n");

            
            #line 529 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"m-portlet mt-4\"");

WriteLiteral(" id=\"commentsContainer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n                            <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"teacherComment\"");

WriteLiteral(" style=\"text-decoration:none;resize:none;min-height:200px;border:none;\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 36463), Tuple.Create("\"", 36574)
            
            #line 538 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 36477), Tuple.Create<System.Object, System.Int32>(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageCommentsPlaceHolder"))
            
            #line default
            #line hidden
, 36477), false)
);

WriteLiteral("></textarea>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-12 mb-2 mt-2\"");

WriteLiteral(" style=\"text-align:end\"");

WriteLiteral(">\r\n                            <button");

WriteAttribute("class", Tuple.Create(" class=\"", 36735), Tuple.Create("\"", 36810)
, Tuple.Create(Tuple.Create("", 36743), Tuple.Create("btn", 36743), true)
, Tuple.Create(Tuple.Create(" ", 36746), Tuple.Create("m-btn--pill", 36747), true)
, Tuple.Create(Tuple.Create(" ", 36758), Tuple.Create("btn-secondary", 36759), true)
            
            #line 541 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 36772), Tuple.Create<System.Object, System.Int32>(iscoordinator ? "coordinator" : ""
            
            #line default
            #line hidden
, 36773), false)
);

WriteLiteral(" id=\"cancelOwnFeedback\"");

WriteLiteral(">");

            
            #line 541 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageClose")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                            <button");

WriteAttribute("class", Tuple.Create(" class=\"", 36964), Tuple.Create("\"", 37083)
, Tuple.Create(Tuple.Create("", 36972), Tuple.Create("btn", 36972), true)
, Tuple.Create(Tuple.Create(" ", 36975), Tuple.Create("m-btn--pill", 36976), true)
, Tuple.Create(Tuple.Create(" ", 36987), Tuple.Create("m-btn", 36988), true)
, Tuple.Create(Tuple.Create(" ", 36993), Tuple.Create("m-btn--gradient-from-brand", 36994), true)
, Tuple.Create(Tuple.Create(" ", 37020), Tuple.Create("m-btn--gradient-to-brand", 37021), true)
            
            #line 542 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    , Tuple.Create(Tuple.Create(" ", 37045), Tuple.Create<System.Object, System.Int32>(iscoordinator ? "coordinator" : ""
            
            #line default
            #line hidden
, 37046), false)
);

WriteLiteral(" id=\"addCommentBtnSave\"");

WriteLiteral(">");

            
            #line 542 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                                                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageSubmit")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        </div>\r\n                    </div>\r\n          " +
"      </div>\r\n\r\n\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-portlet__body m--padding-10\"");

WriteLiteral(">\r\n\r\n                        <!--<div class=\"row mt-4\">\r\n                        " +
"<div class=\"col-xl-12 table-responsive\">\r\n                            <table>\r\n\r" +
"\n                                <tr>\r\n                                    <td><" +
"b>");

            
            #line 564 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageSubmissionStatus")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n");

            
            #line 565 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 565 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                     if (Model.SubmissionStatus == "submitted")
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td");

WriteLiteral(" class=\"m--font-success\"");

WriteLiteral(">");

            
            #line 567 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                               Write(Model.SubmissionStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 568 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td");

WriteLiteral(" class=\"m--font-brand\"");

WriteLiteral(">");

            
            #line 571 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                             Write(Model.SubmissionStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 572 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tr>\r\n                                <tr>\r\n\r\n  " +
"                                  <td><b>");

            
            #line 576 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGradingStatus")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n");

            
            #line 577 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 577 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                     if (Model.GradingStatus == "graded")
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td");

WriteLiteral(" class=\"m--font-success\"");

WriteLiteral(">");

            
            #line 579 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                               Write(Model.GradingStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 580 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td");

WriteLiteral(" class=\"m--font-brand\"");

WriteLiteral(">");

            
            #line 583 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                             Write(Model.GradingStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 584 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tr>\r\n");

            
            #line 586 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 586 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                 if (Model.FeedbackComments != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n\r\n                                     " +
"   <td><b>");

            
            #line 590 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                          Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageFeedback")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n\r\n                                        <td>");

            
            #line 592 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                       Write(Html.Raw(Model.FeedbackComments.FirstOrDefault()));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    </tr>\r\n");

            
            #line 594 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <tr>\r\n                                    <td><" +
"b>");

            
            #line 597 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrade")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n");

            
            #line 598 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 598 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                     if (Model.Grade != "" && Model.Grade != null)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td>\r\n");

WriteLiteral("                                            ");

            
            #line 601 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                       Write(Html.Raw(Model.Grade));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n");

            
            #line 603 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td></td>\r\n");

            
            #line 607 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tr>\r\n                                <tr>\r\n    " +
"                                <td><b>");

            
            #line 610 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageDueDate")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n                                    <td>");

            
            #line 611 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                   Write(Model.DueDate);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>-->\r\n                        ");

WriteLiteral("\r\n                        <!--<tr>\r\n                            <td><b>");

            
            #line 638 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageExtensionDate")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n");

            
            #line 639 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 639 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                             if (Model.ExtensionDueDate != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <td>");

            
            #line 641 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                               Write(Model.ExtensionDueDate);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 642 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tr>\r\n\r\n                        <tr>\r\n                  " +
"          <td><b>");

            
            #line 646 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageLastModified")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n                            <td>");

            
            #line 647 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                           Write(Model.LastModified);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n                        <tr>\r\n             " +
"               <td><b>");

            
            #line 650 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageSubmissionComments")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>-->\r\n                        ");

WriteLiteral("\r\n                        <!--</tr>\r\n                                </table>\r\n\r\n" +
"                            </div>\r\n\r\n                        </div>-->\r\n");

            
            #line 693 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 693 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                          
                            var today = DateTime.Now;
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 696 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 696 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                         if (Model.SubmissionStatus == "submitted" || (Model.SubmissionStatus == "draft" && Model.DueDate.Value < today))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"row mt-4\"");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n\r\n\r\n                                <div");

WriteLiteral(" class=\"col-xl-4 mt-1 mb-1\"");

WriteLiteral(">\r\n                                    <button");

WriteAttribute("class", Tuple.Create(" class=\"", 46265), Tuple.Create("\"", 46324)
, Tuple.Create(Tuple.Create("", 46273), Tuple.Create("btn", 46273), true)
, Tuple.Create(Tuple.Create(" ", 46276), Tuple.Create("btn-brand", 46277), true)
            
            #line 702 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 46286), Tuple.Create<System.Object, System.Int32>(iscoordinator ? "coordinator" : ""
            
            #line default
            #line hidden
, 46287), false)
);

WriteLiteral(" id=\"GradeBTnToMoodleLMSPage\"");

WriteLiteral(">");

            
            #line 702 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrade")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <div");

WriteLiteral(" class=\"col-xl-4 mt-1 mb-1\"");

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-xl-4 mt-1\"");

WriteLiteral(">\r\n                                    <button");

WriteAttribute("class", Tuple.Create(" class=\"", 46699), Tuple.Create("\"", 46763)
, Tuple.Create(Tuple.Create("", 46707), Tuple.Create("btn", 46707), true)
, Tuple.Create(Tuple.Create(" ", 46710), Tuple.Create("btn-brand", 46711), true)
, Tuple.Create(Tuple.Create(" ", 46720), Tuple.Create("mb-1", 46721), true)
            
            #line 707 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 46725), Tuple.Create<System.Object, System.Int32>(iscoordinator ? "coordinator" : ""
            
            #line default
            #line hidden
, 46726), false)
);

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#m_scrollable_modal_1\"");

WriteLiteral(">");

            
            #line 707 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrantextension")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                            </" +
"div>\r\n");

            
            #line 710 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"row mt-4\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-3\"");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" id=\"prevBtn\"");

WriteLiteral(" class=\"btn btn-prev\"");

WriteLiteral(">");

            
            #line 716 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                             Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPagePrevious")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(">\r\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-3\"");

WriteLiteral(" style=\"text-align:end\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" id=\"nextBtn\"");

WriteLiteral(" class=\"btn btn-next\"");

WriteLiteral(">");

            
            #line 722 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                             Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageNext")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </div>\r\n                </div>\r\n            </div>" +
"\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"m_scrollable_modal_1\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" style=\"margin-top:55px\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"files\"");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLabel\"");

WriteLiteral(">");

            
            #line 736 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                          Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrantExtension11")));

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"m-scrollable\"");

WriteLiteral(" data-scrollbar-shown=\"true\"");

WriteLiteral(" data-scrollable=\"true\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"grantExtensionDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 48653), Tuple.Create("\"", 48764)
            
            #line 743 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
    , Tuple.Create(Tuple.Create("", 48667), Tuple.Create<System.Object, System.Int32>(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageSelectDateAndTime11"))
            
            #line default
            #line hidden
, 48667), false)
);

WriteLiteral(" style=\"width:100%; cursor:pointer\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"closeExtension\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 747 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                    Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageClose")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <button");

WriteLiteral(" id=\"saveExtensions\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 748 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageAccept")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n\r\n");

WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"grade_modal_1\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" style=\"margin-top:55px\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"files\"");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"\"");

WriteLiteral(">");

            
            #line 783 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrade")));

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"m-scrollable\"");

WriteLiteral(" data-scrollbar-shown=\"true\"");

WriteLiteral(" data-scrollable=\"true\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"gradeInput\"");

WriteLiteral(" type=\"number\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"100\"");

WriteLiteral(" value=\"\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 51530), Tuple.Create("\"", 51627)
            
            #line 790 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                , Tuple.Create(Tuple.Create("", 51544), Tuple.Create<System.Object, System.Int32>(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageGrade"))
            
            #line default
            #line hidden
, 51544), false)
);

WriteLiteral(" style=\"width:100%; cursor:pointer\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"closeGrade\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 794 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageClose")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <button");

WriteLiteral(" id=\"saveGrade\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 795 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionsPageSave")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<span hidden" +
"");

WriteLiteral(" id=\"stringNextFullName\"");

WriteLiteral(">");

            
            #line 801 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                Write(stringNextFullName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 802 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
 if (Model.ScormOverallGrade != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <span hidden");

WriteLiteral(" id=\"stringValueChart\"");

WriteLiteral(">");

            
            #line 804 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                                  Write(Model.ScormOverallGrade.Replace('%', ' '));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 805 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <span hidden");

WriteLiteral(" id=\"stringValueChart\"");

WriteLiteral("></span>\r\n");

            
            #line 809 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<span hidden");

WriteLiteral(" id=\"stringUserId\"");

WriteLiteral(">");

            
            #line 810 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
                          Write(ViewBag.userId);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 813 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
Write(Scripts.Render("~/assets/vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 814 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
Write(Scripts.Render("~/assets/vendors/bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar-tn.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 815 "..\..\Views\StudentsSubmissionPage\_SubmissionDetails.cshtml"
Write(Scripts.Render("~/assets/vendors/bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr-CH.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
