#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\Resources\_Grades.cshtml"
    using Everest.OpenCurate.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Resources\_Grades.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Resources/_Grades.cshtml")]
    public partial class _Views_Resources__Grades_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Everest.OpenCurate.EntityFramework.EDM.Grade>>
    {
        public _Views_Resources__Grades_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Resources\_Grades.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;
    int gradeIndex = 0;
    int CurrentLanguageIdentifier = (int)ViewBag.CurrentLanguageIdentifier;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<h2");

WriteLiteral(" class=\"widget-title\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"m-menu__link-icon fa fa-cubes mr-2\"");

WriteLiteral(" style=\"font-size:2.5rem;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"ml-2\"");

WriteLiteral(" style=\"font-family:\'poppins\'; font-size:2rem\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Resources\_Grades.cshtml"
                                                                                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "ResourcesPageGrade")));

            
            #line default
            #line hidden
WriteLiteral("</span></i>\r\n    <i");

WriteLiteral(" class=\"show_grade m-menu__ver-arrow la m--pull-right mt-3\"");

WriteLiteral(" data-status=\"none\"");

WriteLiteral(" style=\"color: #2b2350\"");

WriteLiteral("></i>\r\n    ");

WriteLiteral("\r\n</h2>\r\n<ul");

WriteLiteral(" id=\"grades_list\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\Resources\_Grades.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Resources\_Grades.cshtml"
     foreach (Grade grade in Model.Distinct().OrderBy(g => g.GradeIndex))
    {
        string gradeValue = grade.Grade1;

        try
        {
            gradeValue = CurrentLanguageIdentifier == 0 ? grade.Grade1 : grade.DataGUID.DataTranslations.Where(dt => dt.LanguageKey == CurrentLanguageIdentifier).FirstOrDefault().Value;

        }catch(Exception e)
        {
            gradeValue = grade.Grade1;
        }



            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"Grade_Filter\"");

WriteLiteral(" style=\"cursor:pointer\"");

WriteLiteral(" data-key=\"");

            
            #line 31 "..\..\Views\Resources\_Grades.cshtml"
                                                             Write(grade.GradeKey);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-index=\"");

            
            #line 31 "..\..\Views\Resources\_Grades.cshtml"
                                                                                          Write(gradeIndex);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <a>");

            
            #line 32 "..\..\Views\Resources\_Grades.cshtml"
          Write(gradeValue);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <span");

WriteLiteral(" class=\"m-badge m-badge--brand\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Resources\_Grades.cshtml"
                                            Write(Model.Count(c => c.GradeKey == grade.GradeKey).ToString());

            
            #line default
            #line hidden
WriteLiteral("</span><span");

WriteLiteral(" class=\"remove m-badge m-badge--danger\"");

WriteLiteral(" data-key=\"");

            
            #line 33 "..\..\Views\Resources\_Grades.cshtml"
                                                                                                                                                                    Write(grade.GradeKey);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-display=\"false\"");

WriteLiteral(" style=\"display:none; margin-left:10px \"");

WriteLiteral(" title=\"click to remove\"");

WriteLiteral(">X</span>\r\n        </li>\r\n");

            
            #line 35 "..\..\Views\Resources\_Grades.cshtml"
        gradeIndex++;
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
