#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 3 "..\..\Views\Resources\Details.cshtml"
    using Everest.OpenCurate.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Resources\Details.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Resources/Details.cshtml")]
    public partial class _Views_Resources_Details_cshtml : System.Web.Mvc.WebViewPage<Everest.OpenCurate.EntityFramework.EDM.Candidate>
    {
        public _Views_Resources_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Resources\Details.cshtml"
  
    TempData["DisplayLeftAssistant"] = true;

    var candidate = Model;
    Dictionary<string, string> Locale = ViewBag.Locale;
    ViewBag.Title = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "ResourcesPageDetailsResourceDetails"));
    List<CuratedLessonType> curatedLessonTypes = new List<CuratedLessonType>();
    if (candidate.StatusKey == 3)
    {
        curatedLessonTypes.AddRange(candidate.Lessons.SelectMany(l => l.CuratedLessonTypes).ToList());
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    ");

WriteLiteral(@"@media (min-width: 1200px) {
        .container {
            max-width: 90%;
        }
    }

    .page-banner {
        margin-top: 95px !important;
        height: fit-content;
        margin-bottom: 30px;
        background-color: #ffffff;
    }

    .page-body {
        padding: 0;
        margin-bottom: 50px;
    }

    ");

WriteLiteral(@"@media (max-width: 575px) {
        .col-xm-12 {
            text-align: center;
        }

        .m-portlet__body {
            padding-right: 0px !important;
            padding-left: 0px !important;
        }

        .open_book {
            margin-left: 0px !important;
        }
    }

    .image-portlet {
        width: 100%;
        height: auto;
        text-align: center;
    }

    .m-portlet img {
        width: auto;
        max-height: 650px;
        box-shadow: 10px 10px 10px #ccc;
        -moz-box-shadow: 10px 10px 10px #ccc;
        -webkit-box-shadow: 10px 10px 10px #ccc;
        cursor: pointer;
    }

    .cadre {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }

    .m-portlet.m-portlet--sticky .m-portlet__head {
        width: 100% !important;
    }

    svg {
        height: 50px
    }

    .blog-post-archive {
        padding: 80px 0;
    }
</style>
");

            
            #line 85 "..\..\Views\Resources\Details.cshtml"
Write(Styles.Render("~/assets/vendors/chartist/dist/chartist.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<section");

WriteLiteral(" class=\"page-banner\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"page-title-wrapper\"");

WriteLiteral(">\r\n            <div>\r\n                <ul");

WriteLiteral(" class=\"bradcurmed\"");

WriteLiteral(">\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2202), Tuple.Create("\"", 2241)
            
            #line 92 "..\..\Views\Resources\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2209), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Dashboard")
            
            #line default
            #line hidden
, 2209), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 92 "..\..\Views\Resources\Details.cshtml"
                                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Wall")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2364), Tuple.Create("\"", 2403)
            
            #line 93 "..\..\Views\Resources\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2371), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Resources")
            
            #line default
            #line hidden
, 2371), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 93 "..\..\Views\Resources\Details.cshtml"
                                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_OER")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                    <li><a");

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 94 "..\..\Views\Resources\Details.cshtml"
                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "ResourcesPageDetails")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                </ul>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row m--margin-top-20-desktop\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-1 m-auto m--hidden-mobile\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 99 "..\..\Views\Resources\Details.cshtml"
               Write(Html.Partial("~/Views/SharedSvgs/_DigitalLibraryIcon.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-5 col-12 m-auto\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">");

            
            #line 102 "..\..\Views\Resources\Details.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "ResourcesPageDetailsResourceDetails")));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-3  m-auto\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-3 col-12 m-auto\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n\r\n    </div>\r\n  " +
"  <!-- /.container -->\r\n</section>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div>\r\n\r\n        <div");

WriteLiteral(" class=\"m-portlet__body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"display:flex; align-items:center; justify-content:center\"");

WriteLiteral(" class=\"m-4\"");

WriteLiteral(">\r\n                <h1");

WriteLiteral(" style=\"color:#f98e47 !important\"");

WriteLiteral(">");

            
            #line 122 "..\..\Views\Resources\Details.cshtml"
                                                Write(candidate.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"cadre\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"padding:20px\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"image\"");

WriteLiteral(" class=\"image-portlet\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3801), Tuple.Create("\"", 3885)
            
            #line 127 "..\..\Views\Resources\Details.cshtml"
, Tuple.Create(Tuple.Create("", 3807), Tuple.Create<System.Object, System.Int32>(Url.Action("Screenshot", "Files").ToString() + "/" + candidate.CandidateKey
            
            #line default
            #line hidden
, 3807), false)
);

WriteLiteral(" class=\"\"");

WriteLiteral(" alt=\"...\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding:15px\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-12 mt-1\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" style=\"display:flex; align-items:center; justify-content:center\"");

WriteLiteral(">\r\n                                <span>\r\n                                    <i" +
"");

WriteLiteral(" class=\"fa fa-link m-1\"");

WriteLiteral("></i>\r\n                                </span>\r\n                                <" +
"a");

WriteAttribute("href", Tuple.Create(" href=\"", 4331), Tuple.Create("\"", 4352)
            
            #line 135 "..\..\Views\Resources\Details.cshtml"
, Tuple.Create(Tuple.Create("", 4338), Tuple.Create<System.Object, System.Int32>(candidate.URL
            
            #line default
            #line hidden
, 4338), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" style=\"word-break:break-all\"");

WriteLiteral(">");

            
            #line 135 "..\..\Views\Resources\Details.cshtml"
                                                                                                 Write(candidate.URL);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </span>\r\n                        </div>\r\n      " +
"              </div>\r\n                </div>\r\n\r\n            </div>\r\n\r\n          " +
"  <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin-top:35px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-2 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fab fa-sistrix fa-7x\"");

WriteLiteral("> </i>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 154 "..\..\Views\Resources\Details.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageSubject")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span><br>\r\n\r\n                        " +
"            </span>\r\n                                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 160 "..\..\Views\Resources\Details.cshtml"
                                       Write(candidate.Subject.Subject1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"col-lg-8 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-heading fa-7x\"");

WriteLiteral("> </i>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 178 "..\..\Views\Resources\Details.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageTopic")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span>");

WriteLiteral("\r\n                                    </span>\r\n                                  " +
"  <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 186 "..\..\Views\Resources\Details.cshtml"
                                       Write(candidate.LearningOutcome.LearningOutcome1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div");

WriteLiteral(" class=\"col-lg-2 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-graduation-cap fa-7x\"");

WriteLiteral("> </i>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 205 "..\..\Views\Resources\Details.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageGrade")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span><br>\r\n\r\n                        " +
"            </span>\r\n                                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 211 "..\..\Views\Resources\Details.cshtml"
                                       Write(candidate.Grade.Grade1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>
            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-3 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-language fa-7x\"");

WriteLiteral("> </i>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 234 "..\..\Views\Resources\Details.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageLanguage")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span><br>\r\n\r\n                        " +
"            </span>\r\n                                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 240 "..\..\Views\Resources\Details.cshtml"
                                       Write(candidate.Language.Language1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div");

WriteLiteral(" class=\"col-lg-3 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-money-bill-alt fa-7x\"");

WriteLiteral("> </i>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 259 "..\..\Views\Resources\Details.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageAccessLevel")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span><br>\r\n\r\n                        " +
"            </span>\r\n                                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 265 "..\..\Views\Resources\Details.cshtml"
                                       Write(candidate.AccessLevel);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div");

WriteLiteral(" class=\"col-lg-3 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget14 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row open_book\"");

WriteLiteral(" style=\"margin-left:6px\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-book-open fa-7x\"");

WriteLiteral("> </i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col\"");

WriteLiteral(">\r\n                                    <div>\r\n                                   " +
"     <div");

WriteLiteral(" id=\"m_chart_profit_share\"");

WriteLiteral(" class=\"m-widget14__chart\"");

WriteLiteral(" style=\"height: 100px\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-widget14__stat\"");

WriteLiteral(" style=\"font-size:1.7em !important\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:#575962;font-size:0.7em !important;\"");

WriteLiteral(">");

            
            #line 284 "..\..\Views\Resources\Details.cshtml"
                                                                                                                                                                 Write(Math.Round((double)candidate.ReadabilityScore, 2));

            
            #line default
            #line hidden
WriteLiteral("/5</span></div>\r\n                                        </div>\r\n                " +
"                    </div>\r\n                                </div>\r\n            " +
"                    <div");

WriteLiteral(" class=\"col\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"m-widget14__legends\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"m-widget14__legend\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget14__legend-bullet m--bg-brand\"");

WriteLiteral("></span>\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">");

            
            #line 292 "..\..\Views\Resources\Details.cshtml"
                                                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageReadabilityScore")));

            
            #line default
            #line hidden
WriteLiteral(@"</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"col-lg-3 col-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-globe fa-7x\"");

WriteLiteral("> </i>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 310 "..\..\Views\Resources\Details.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPagePublisher")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span><br>\r\n\r\n                        " +
"            </span>\r\n                                    <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 316 "..\..\Views\Resources\Details.cshtml"
                                       Write(candidate.Publisher.Publisher1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
");

            
            #line 327 "..\..\Views\Resources\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 327 "..\..\Views\Resources\Details.cshtml"
             if (candidate.StatusKey == 3 && curatedLessonTypes.Count > 0)
            {
                var tags = candidate.CandidateTags.Where(ct => !ct.Tag.TagsSource.TagSource.Equals("Internal"));
                int tagsCount = tags.Count();


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"m-login__form-divider m--margin-top-10 m--margin-bottom-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-divider\"");

WriteLiteral(">\r\n                        <span></span>\r\n                        <span>Curator\'s" +
" Feedback</span>\r\n                        <span></span>\r\n                    </d" +
"iv>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-4 col-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-puzzle-piece fa-7x\"");

WriteLiteral("> </i>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 350 "..\..\Views\Resources\Details.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageResourceUsability")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span><br>\r\n\r\n                    " +
"                    </span>\r\n                                        <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

            
            #line 356 "..\..\Views\Resources\Details.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 356 "..\..\Views\Resources\Details.cshtml"
                                                  
                                                    var resourceUsabilities = curatedLessonTypes.Where(l => l.LessonType.ParentLessonType.Equals("ResourceUsability"));

                                                    foreach (var item in resourceUsabilities)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <span");

WriteLiteral(" class=\"m-badge m-badge--brand m-badge--wide\"");

WriteLiteral(">");

            
            #line 361 "..\..\Views\Resources\Details.cshtml"
                                                                                                      Write(item.LessonType.LessonType1);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 362 "..\..\Views\Resources\Details.cshtml"
                                                    }
                                                
            
            #line default
            #line hidden
WriteLiteral(@"
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div");

WriteLiteral(" class=\"col-lg-4 col-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-filter fa-7x\"");

WriteLiteral("> </i>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 382 "..\..\Views\Resources\Details.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageResourceType")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span><br>\r\n\r\n                    " +
"                    </span>\r\n                                        <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

            
            #line 388 "..\..\Views\Resources\Details.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 388 "..\..\Views\Resources\Details.cshtml"
                                                  
                                                    var resourceTypes = curatedLessonTypes.Where(l => l.LessonType.ParentLessonType.Equals("ResourceType"));
                                                    foreach (var item in resourceTypes)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <span");

WriteLiteral(" class=\"m-badge m-badge--brand m-badge--wide\"");

WriteLiteral(">");

            
            #line 392 "..\..\Views\Resources\Details.cshtml"
                                                                                                      Write(item.LessonType.LessonType1);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 393 "..\..\Views\Resources\Details.cshtml"
                                                    }
                                                
            
            #line default
            #line hidden
WriteLiteral(@"
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div");

WriteLiteral(" class=\"col-lg-4 col-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-ruler-combined fa-7x\"");

WriteLiteral("> </i>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 413 "..\..\Views\Resources\Details.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageMasteryScale")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span><br>\r\n\r\n                    " +
"                    </span>\r\n                                        <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

            
            #line 419 "..\..\Views\Resources\Details.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 419 "..\..\Views\Resources\Details.cshtml"
                                                  
                                                    var masteryScale = curatedLessonTypes.Where(l => l.LessonType.ParentLessonType.Equals("MasteryScale"));
                                                    foreach (var item in masteryScale)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <span");

WriteLiteral(" class=\"m-badge m-badge--brand m-badge--wide\"");

WriteLiteral(">");

            
            #line 423 "..\..\Views\Resources\Details.cshtml"
                                                                                                      Write(item.LessonType.LessonType1);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 424 "..\..\Views\Resources\Details.cshtml"
                                                    }
                                                
            
            #line default
            #line hidden
WriteLiteral(@"
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                </div>
");

WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 21612), Tuple.Create("\"", 21670)
            
            #line 438 "..\..\Views\Resources\Details.cshtml"
, Tuple.Create(Tuple.Create("", 21620), Tuple.Create<System.Object, System.Int32>(tagsCount == 0 ? "col-lg-6" : "col-lg-4"
            
            #line default
            #line hidden
, 21620), false)
, Tuple.Create(Tuple.Create(" ", 21663), Tuple.Create("col-12", 21664), true)
);

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-key fa-7x\"");

WriteLiteral("> </i>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 448 "..\..\Views\Resources\Details.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageResourceResourceAccessibility")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span><br>\r\n\r\n                    " +
"                    </span>\r\n                                        <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(">\r\n");

            
            #line 454 "..\..\Views\Resources\Details.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 454 "..\..\Views\Resources\Details.cshtml"
                                                  
                                                    var resourceAccessibilities = curatedLessonTypes.Where(l => l.LessonType.ParentLessonType.Equals("Resource Accessibility"));
                                                    foreach (var item in resourceAccessibilities)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <span");

WriteLiteral(" class=\"m-badge m-badge--brand m-badge--wide\"");

WriteLiteral(">");

            
            #line 458 "..\..\Views\Resources\Details.cshtml"
                                                                                                      Write(item.LessonType.LessonType1);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 459 "..\..\Views\Resources\Details.cshtml"
                                                    }
                                                
            
            #line default
            #line hidden
WriteLiteral(@"
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 23675), Tuple.Create("\"", 23733)
            
            #line 469 "..\..\Views\Resources\Details.cshtml"
, Tuple.Create(Tuple.Create("", 23683), Tuple.Create<System.Object, System.Int32>(tagsCount == 0 ? "col-lg-6" : "col-lg-4"
            
            #line default
            #line hidden
, 23683), false)
, Tuple.Create(Tuple.Create(" ", 23726), Tuple.Create("col-12", 23727), true)
);

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget1 cadre\"");

WriteLiteral(" style=\"margin-top:10px; height:90%;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-widget4__item\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-book-open fa-7x\"");

WriteLiteral("> </i>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-widget4__info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 479 "..\..\Views\Resources\Details.cshtml"
                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageAssignedReadability")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span><br>\r\n\r\n                    " +
"                    </span>\r\n                                        <div");

WriteLiteral(" class=\"m-widget4__ext\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"m-widget4__number m--font-brand\"");

WriteLiteral(" style=\"font-size:1.7em !important\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" style=\"color:#575962;font-size:0.7em !important;\"");

WriteLiteral(">");

            
            #line 485 "..\..\Views\Resources\Details.cshtml"
                                                                                                   Write(Math.Round(candidate.Lessons.Select(l => l.ReadabilityRate).FirstOrDefault().Value, 0));

            
            #line default
            #line hidden
WriteLiteral(@"/5</span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    ");

WriteLiteral("\r\n                </div>\r\n");

            
            #line 528 "..\..\Views\Resources\Details.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n\r\n</div>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"m_modal_5\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" style=\"z-index:9999;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-sm\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLabel\"");

WriteLiteral(">");

            
            #line 540 "..\..\Views\Resources\Details.cshtml"
                                                          Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageRejection")));

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <form>\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"message-text\"");

WriteLiteral(" class=\"form-control-label\"");

WriteLiteral(">");

            
            #line 552 "..\..\Views\Resources\Details.cshtml"
                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageRejectionReason")));

            
            #line default
            #line hidden
WriteLiteral(":</label>\r\n                        <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"rejectionReason\"");

WriteLiteral("></textarea>\r\n                    </div>\r\n                </form>\r\n            </" +
"div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"saveRejectionBtn\"");

WriteLiteral(">");

            
            #line 558 "..\..\Views\Resources\Details.cshtml"
                                                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageSaveBtn")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 559 "..\..\Views\Resources\Details.cshtml"
                                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "CurateDetailsPageCancelBtn")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 565 "..\..\Views\Resources\Details.cshtml"
 using (Html.BeginForm("RejectCandidate", "Curate", FormMethod.Post, new { id = "RejectCandidateHidden", @class = "", @style = "display:none;" }))
{

    
            
            #line default
            #line hidden
            
            #line 568 "..\..\Views\Resources\Details.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 568 "..\..\Views\Resources\Details.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 569 "..\..\Views\Resources\Details.cshtml"
Write(Html.Hidden("candidateKey", ""));

            
            #line default
            #line hidden
            
            #line 569 "..\..\Views\Resources\Details.cshtml"
                                    
    
            
            #line default
            #line hidden
            
            #line 570 "..\..\Views\Resources\Details.cshtml"
Write(Html.Hidden("reasonOfRejection", ""));

            
            #line default
            #line hidden
            
            #line 570 "..\..\Views\Resources\Details.cshtml"
                                         
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 574 "..\..\Views\Resources\Details.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 575 "..\..\Views\Resources\Details.cshtml"
Write(Scripts.Render("~/assets/vendors/chartist/dist/chartist.js"));

            
            #line default
            #line hidden
WriteLiteral(@"

<script>
        $(""#footer"").remove();
        $("".BodyParent"").removeClass('m--padding-top-90');
        $('.RenderBody').removeClass('col-lg-9 col-md-9');
        $('.RenderBody').prev().remove();

    $('meta[name=""keywords""]').remove();
    $('head').append('<meta name=""keywords"" content=""");

            
            #line 584 "..\..\Views\Resources\Details.cshtml"
                                                Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\" />\');\r\n        //** Based on Chartist plugin - https://gionkunz.github.io/chart" +
"ist-js/index.html\r\n        function profitShare() {\r\n            if ($(\'#m_chart" +
"_profit_share\').length == 0) {\r\n                return;\r\n            }\r\n        " +
"    var chart = new Chartist.Pie(\'#m_chart_profit_share\', {\r\n                ser" +
"ies: [{\r\n                    value: 1.9,\r\n                    className: \'custom" +
"\',\r\n                    meta: {\r\n                        color: \'#f98e47\'\r\n     " +
"               }\r\n                },\r\n                {\r\n                    val" +
"ue: 5,\r\n                    className: \'custom\',\r\n                    meta: {\r\n " +
"                       color: \'#d0ced9\'\r\n                    }\r\n                " +
"},\r\n                ],\r\n                labels: [1, 2, 3]\r\n            }, {\r\n   " +
"             donut: true,\r\n                donutWidth: 10,\r\n                show" +
"Label: false\r\n            });\r\n\r\n            chart.on(\'draw\', function (data) {\r" +
"\n                if (data.type === \'slice\') {\r\n                    // Get the to" +
"tal path length in order to use for dash array animation\r\n                    va" +
"r pathLength = data.element._node.getTotalLength();\r\n\r\n                    // Se" +
"t a dasharray that matches the path length as prerequisite to animate dashoffset" +
"\r\n                    data.element.attr({\r\n                        \'stroke-dasha" +
"rray\': pathLength + \'px \' + pathLength + \'px\'\r\n                    });\r\n\r\n      " +
"              // Create animation definition while also assigning an ID to the a" +
"nimation for later sync usage\r\n                    var animationDefinition = {\r\n" +
"                        \'stroke-dashoffset\': {\r\n                            id: " +
"\'anim\' + data.index,\r\n                            dur: 1000,\r\n                  " +
"          from: -pathLength + \'px\',\r\n                            to: \'0px\',\r\n   " +
"                         easing: Chartist.Svg.Easing.easeOutQuint,\r\n            " +
"                // We need to use `fill: \'freeze\'` otherwise our animation will " +
"fall back to initial (not visible)\r\n                            fill: \'freeze\',\r" +
"\n                            \'stroke\': data.meta.color\r\n                        " +
"}\r\n                    };\r\n\r\n                    // If this was not the first sl" +
"ice, we need to time the animation so that it uses the end sync event of the pre" +
"vious animation\r\n                    if (data.index !== 0) {\r\n                  " +
"      animationDefinition[\'stroke-dashoffset\'].begin = \'anim\' + (data.index - 1)" +
" + \'.end\';\r\n                    }\r\n\r\n                    // We need to set an in" +
"itial value before the animation starts as we are not in guided mode which would" +
" do that for us\r\n\r\n                    data.element.attr({\r\n                    " +
"    \'stroke-dashoffset\': -pathLength + \'px\',\r\n                        \'stroke\': " +
"data.meta.color\r\n                    });\r\n\r\n                    // We can\'t use " +
"guided mode as the animations need to rely on setting begin manually\r\n          " +
"          // See http://gionkunz.github.io/chartist-js/api-documentation.html#ch" +
"artistsvg-function-animate\r\n                    data.element.animate(animationDe" +
"finition, false);\r\n                }\r\n            });\r\n\r\n            // For the " +
"sake of the example we update the chart every time it\'s created with a delay of " +
"8 seconds\r\n            return;\r\n\r\n            /*\r\n            chart.on(\'created\'" +
", function() {\r\n                if (window.__anim21278907124) {\r\n               " +
"     clearTimeout(window.__anim21278907124);\r\n                    window.__anim2" +
"1278907124 = null;\r\n                }\r\n                window.__anim21278907124 " +
"= setTimeout(chart.update.bind(chart), 15000);\r\n            });\r\n            */\r" +
"\n        }\r\n        $(\'document\').ready(function () {\r\n            //profitShare" +
"();\r\n            //$(\'#image\').click(function () {\r\n            //    window.ope" +
"n(\'http://tofoula-mourahaka.blogspot.com/2013/11/blog-post_4153.html\', \'_blank\')" +
";\r\n            //});\r\n        });\r\n\r\n        $(\"#curateBtn\").click(function () {" +
"\r\n             mApp.block($(\"#WholePageDiv\"));\r\n              window.location = " +
"\'");

            
            #line 677 "..\..\Views\Resources\Details.cshtml"
                            Write(Url.Action("ResourceUsability","Curate"));

            
            #line default
            #line hidden
WriteLiteral("/\' + \'");

            
            #line 677 "..\..\Views\Resources\Details.cshtml"
                                                                           Write(ViewBag.candidateId);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        })\r\n\r\n        $(\"#backBtn\").click(function () {\r\n            mApp.blo" +
"ck($(\"#WholePageDiv\"));\r\n              //window.location = \'");

            
            #line 682 "..\..\Views\Resources\Details.cshtml"
                              Write(Url.Action("Index","Curate"));

            
            #line default
            #line hidden
WriteLiteral(@"';
            history.back();
        })

        $(""#saveRejectionBtn"").click(function () {
            var reason = $(""#rejectionReason"").val();
            if (reason != '') {
                mApp.block($(""#WholePageDiv""));
                mApp.block($("".modal-content""));

                $(""#candidateKey"").val('");

            
            #line 692 "..\..\Views\Resources\Details.cshtml"
                                   Write(ViewBag.candidateId);

            
            #line default
            #line hidden
WriteLiteral(@"');
                $(""#reasonOfRejection"").val(reason);

                $(""#RejectCandidateHidden"").ajaxSubmit({
                    beforeSubmit: function () {
                    },
                    success: function (data) {
                        if (data == 2) {
                            mApp.unblock($(""#WholePageDiv""));
                            window.location = '");

            
            #line 701 "..\..\Views\Resources\Details.cshtml"
                                          Write(Url.Action("Index","Curate"));

            
            #line default
            #line hidden
WriteLiteral(@"';
                        } else {
                            mApp.unblock($(""#WholePageDiv""));
                            mApp.unblock($("".modal-content""));
                        }
                    },
                    error: function (xhr, status, error) {
                        console.log(""Error In RejectCandidateHidden !!!!!!!"");
                        mApp.unblock($(""#WholePageDiv""));
                        mApp.unblock($("".modal-content""));
                    }
                });
            } else {
                               ");

WriteLiteral("\r\n                $(\"#rejectionReason\").css(\"border-color\", \"red\");\r\n            " +
"    mApp.unblock($(\".modal-content\"));\r\n            }\r\n\r\n         })\r\n</script>\r" +
"\n\r\n\r\n");

});

        }
    }
}
#pragma warning restore 1591
