#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SynchronousSessions/_SynchronousSessionEditSelectAudience.cshtml")]
    public partial class _Views_SynchronousSessions__SynchronousSessionEditSelectAudience_cshtml : System.Web.Mvc.WebViewPage<RLI.WebApplication.Models.SynchronousSessionSelectAudienceViewModel>
    {
        public _Views_SynchronousSessions__SynchronousSessionEditSelectAudience_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    ul {\r\n        list-style-type: none;\r\n    }\r\n</style>\r\n\r\n");

            
            #line 14 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
 using (Html.BeginForm("SessionEditSelectAudience", "SynchronousSessions", FormMethod.Post, new { @class = "m-form m-form--label-align-left", @id = "sessionEditSelectedAudienceForm", role = "form", novalidate = "novalidate" }))
{
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-1 col-12\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"col-md-10 col-12\"");

WriteLiteral(">\r\n            <!-- to move to partial -->\r\n            <div");

WriteLiteral(" class=\"m-form__heading\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"font-weight-bold\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageEditSelectAudience")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h3>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"mt-5\"");

WriteLiteral(">\r\n\r\n");

            
            #line 29 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                 if (RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name == "Student" && ViewBag.ClassTeacher != null)
                {
                    Teacher ClassTeacher = ViewBag.ClassTeacher;
                    Timeline ClassTeacherSelected = ViewBag.ClassTeacherSelected;

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-4 col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 35 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageEditSelectTeacherAudience")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-8 col-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" id=\"enrolled_students\"");

WriteLiteral(" style=\"min-height:100px\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <ul>\r\n                                    <li>\r" +
"\n");

            
            #line 45 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                         if (ClassTeacherSelected != null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <label");

WriteLiteral(" class=\"m-checkbox\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" class=\"teacher\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"selectTeacher\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2362), Tuple.Create("\"", 2394)
            
            #line 48 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                   , Tuple.Create(Tuple.Create("", 2370), Tuple.Create<System.Object, System.Int32>(ClassTeacher.TeacherKey
            
            #line default
            #line hidden
, 2370), false)
);

WriteLiteral(" checked=\"checked\"");

WriteLiteral(">");

            
            #line 48 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                          Write(ClassTeacher.FirstName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 48 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                                                  Write(ClassTeacher.LastName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                <span></span>\r\n                " +
"                            </label>\r\n");

            
            #line 51 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <label");

WriteLiteral(" class=\"m-checkbox\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" class=\"teacher\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"selectTeacher\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2890), Tuple.Create("\"", 2922)
            
            #line 55 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                   , Tuple.Create(Tuple.Create("", 2898), Tuple.Create<System.Object, System.Int32>(ClassTeacher.TeacherKey
            
            #line default
            #line hidden
, 2898), false)
);

WriteLiteral(" >");

            
            #line 55 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                         Write(ClassTeacher.FirstName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 55 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                                 Write(ClassTeacher.LastName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                <span></span>\r\n                " +
"                            </label>\r\n");

            
            #line 58 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                </ul" +
">\r\n                            </div>\r\n                        </div>\r\n         " +
"           </div>\r\n");

            
            #line 65 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-4 col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 69 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                   Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageEditSelectStudentAudience")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"enrolled_students\"");

WriteLiteral(" style=\"min-height:100px\"");

WriteLiteral(">\r\n\r\n");

            
            #line 74 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                             if (Model.SelectedStudentsEnrolled.Count() == Model.StudentsEnrolled.Count())
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <label");

WriteLiteral(" class=\"m-checkbox m-checkbox--air\"");

WriteLiteral(">\r\n                                    All<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"all_students\"");

WriteLiteral(" data-child=\"students\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" />\r\n                                    <span></span>\r\n                         " +
"       </label>\r\n");

            
            #line 80 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <label");

WriteLiteral(" class=\"m-checkbox m-checkbox--air\"");

WriteLiteral(">\r\n                                    All<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"all_students\"");

WriteLiteral(" data-child=\"students\"");

WriteLiteral(" />\r\n                                    <span></span>\r\n                         " +
"       </label>\r\n");

            
            #line 87 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <ul>\r\n");

            
            #line 90 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                 foreach (var student in Model.StudentsEnrolled)
                                {
                                    
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                               


            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <label");

WriteLiteral(" class=\"m-checkbox\"");

WriteLiteral(">\r\n");

            
            #line 101 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                             if (Model.SelectedStudentsEnrolled.Where(ss => ss.StudentKey == student.StudentKey).Count() > 0)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" class=\"student\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"studentsSelected\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5573), Tuple.Create("\"", 5600)
            
            #line 103 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                      , Tuple.Create(Tuple.Create("", 5581), Tuple.Create<System.Object, System.Int32>(student.StudentKey
            
            #line default
            #line hidden
, 5581), false)
);

WriteLiteral(" checked=\"checked\"");

WriteLiteral(">");

            
            #line 103 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                             
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                        Write(student.StudentName);

            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                                                 
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" class=\"student\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"studentsSelected\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5896), Tuple.Create("\"", 5923)
            
            #line 107 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                      , Tuple.Create(Tuple.Create("", 5904), Tuple.Create<System.Object, System.Int32>(student.StudentKey
            
            #line default
            #line hidden
, 5904), false)
);

WriteLiteral(">");

            
            #line 107 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                           
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                      Write(student.StudentName);

            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"
                                                                                                                                                               
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                            <span></span>\r\n                      " +
"                  </label>\r\n                                    </li>\r\n");

            
            #line 112 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"

                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </div>\r\n              " +
"      </div>\r\n                </div>\r\n\r\n            </div>\r\n        </div>\r\n    " +
"    <div");

WriteLiteral(" class=\"col-md-1 col-12\"");

WriteLiteral("></div>\r\n    </div>\r\n");

            
            #line 123 "..\..\Views\SynchronousSessions\_SynchronousSessionEditSelectAudience.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
