#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 4 "..\..\Views\ToDoList\View.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ToDoList/View.cshtml")]
    public partial class _Views_ToDoList_View_cshtml : System.Web.Mvc.WebViewPage<CleverOwl.WebApplication.Models.ToDoViewModel>
    {
        public _Views_ToDoList_View_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n");

            
            #line 7 "..\..\Views\ToDoList\View.cshtml"
  
    ViewBag.Title = "To Do List";
    Dictionary<string, string> Locale = ViewBag.Locale;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\ToDoList\View.cshtml"
Write(Styles.Render("~/assets/vendors/select2/dist/css/select2.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\ToDoList\View.cshtml"
Write(Styles.Render("~/assets/vendors/jstree/dist/themes/default/style.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\ToDoList\View.cshtml"
Write(Styles.Render("~/assets/vendors/select2/dist/css/select2.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    .select2-results {\r\n        padding: 15% !important;\r\n    }\r\n\r\n\r" +
"\n    svg {\r\n        height: 50px;\r\n    }\r\n\r\n    .page-banner {\r\n        margin-t" +
"op: 45px !important;\r\n        height: fit-content;\r\n        /* margin-bottom: 30" +
"px;*/\r\n        background-color: #ffffff;\r\n        overflow: visible !important;" +
"\r\n    }\r\n  .todos-container{\r\n      margin-top:50px;\r\n  }\r\n    .page-body {\r\n   " +
"     padding: 0;\r\n        margin-bottom: 50px;\r\n    }\r\n\r\n    .grid-card {\r\n     " +
"   box-shadow: rgb(99 99 99 / 20%) 0px 2px 8px 0px;\r\n        border-radius: 25px" +
";\r\n        padding: 40px;\r\n        background: linear-gradient( to left, rgb(115" +
" 110 197 / 80%) 0%, rgb(68 60 182) 100% ) left bottom #ffffff no-repeat;\r\n      " +
"  background-size: 100% 18px;\r\n        cursor: pointer;\r\n    }\r\n\r\n        .grid-" +
"card:hover {\r\n            background: #c3c3c31f;\r\n        }\r\n\r\n\r\n\r\n    .grid-car" +
"d-body {\r\n        margin-top: 25px;\r\n        font-weight: 100;\r\n    }\r\n\r\n    .gr" +
"id-card-footer {\r\n        margin-top: 50px;\r\n        margin-bottom: -10px;\r\n    " +
"}\r\n\r\n    .table-row {\r\n        display: table-row;\r\n        height: auto;\r\n    }" +
"\r\n\r\n    .table-cell1 {\r\n        border: none;\r\n        display: table-cell;\r\n   " +
"     padding: 2px;\r\n        width: 80%\r\n    }\r\n\r\n    .table-cell2 {\r\n        bor" +
"der: none;\r\n        display: table-cell;\r\n        padding: 2px;\r\n    }\r\n\r\n    vi" +
"deo {\r\n        max-width: 398px;\r\n        max-height: 130px;\r\n    }\r\n\r\n\r\n    .se" +
"lect2-selection__clear {\r\n        padding-top: 8px !important;\r\n    }\r\n\r\n    .sh" +
"ow-calendar {\r\n        visibility: hidden;\r\n    }\r\n\r\n    h2 {\r\n        /*font-si" +
"ze: 31px;*/\r\n        width: 100%;\r\n        font-weight: bold;\r\n        text-alig" +
"n: center;\r\n    }\r\n\r\n\r\n    .completed-todo {\r\n        background: #6bff622e;\r\n  " +
"  }\r\n\r\n    .duedate-todo {\r\n        background: #f388881f;\r\n    }\r\n\r\n\r\n    .prev" +
"iousDayBtn, .nextDayBtn {\r\n        background: none;\r\n        border: none;\r\n   " +
"     cursor: pointer;\r\n    }\r\n\r\n    .m-portlet {\r\n        background: #fdfafa;\r\n" +
"        padding: 5px;\r\n    }\r\n\r\n    p {\r\n        margin-top: 10px;\r\n    }\r\n\r\n   " +
" .searchInput {\r\n        width: 100%;\r\n        margin-top: 20px;\r\n    }\r\n\r\n\r\n   " +
" .previousDayBtn i, .nextDayBtn i {\r\n        font-size: 40px;\r\n        color: #f" +
"98e47;\r\n    }\r\n\r\n\r\n    .head-title {\r\n        width: 100%;\r\n        padding: 10p" +
"x;\r\n    }\r\n\r\n        .head-title h3 {\r\n            color: #c3c3c3;\r\n            " +
"padding-left: 33px;\r\n            font-style: italic;\r\n        }\r\n\r\n    #dateText" +
" {\r\n        cursor: pointer;\r\n    }\r\n\r\n    .upper-part {\r\n        margin-top: 24" +
"px;\r\n    }\r\n\r\n    .calendar {\r\n        position: absolute;\r\n        top:30px;\r\n " +
"       left: 50%;\r\n        right: 50%;\r\n        transform: translate(-50%, 10px)" +
";\r\n        z-index: 2;\r\n    }\r\n\r\n    .month-list > div {\r\n        cursor: pointe" +
"r;\r\n    }\r\n\r\n    .arrow-container button {\r\n        background: none;\r\n        b" +
"order: none;\r\n        cursor: pointer;\r\n    }\r\n\r\n    .info-error-container {\r\n  " +
"      margin-top: -19px;\r\n        border-radius: 49px;\r\n        box-shadow: rgba" +
"(0, 0, 0, 0.35) 0px 5px 15px;\r\n        background: white;\r\n        padding: 11px" +
" 20px;\r\n    }\r\n\r\n    #go-mobile {\r\n        display: none;\r\n    }\r\n\r\n    .courseB" +
"tn {\r\n        border: 0;\r\n        padding: 10px 20px;\r\n        border-radius: 16" +
"px;\r\n        margin-top: 10px;\r\n        color: #2b2376;\r\n        background: #f9" +
"f5f7;\r\n    }\r\n\r\n        .courseBtn:hover {\r\n            color: white;\r\n         " +
"   background: #f98e47;\r\n        }\r\n\r\n    .show-grades {\r\n        display: none;" +
"\r\n    }\r\n\r\n    .gradefilterAll {\r\n        background: rgb(43, 35, 80);\r\n        " +
"color: white;\r\n    }\r\n\r\n    .gradeBtn:hover {\r\n        color: white;\r\n        ba" +
"ckground: rgb(43, 35, 80);\r\n    }\r\n\r\n\r\n    ");

WriteLiteral("@media(max-width:985px) {\r\n        .head-title h3 {\r\n            padding-left: 34" +
"px;\r\n        }\r\n\r\n        p {\r\n            margin-top: 0px;\r\n        }\r\n    }\r\n\r" +
"\n\r\n\r\n\r\n\r\n    ");

WriteLiteral(@"@media(max-width:580px) {

       /* h2 {
            font-size: 1.1em;
        }*/

        .m-accordion {
            display: none;
        }

        .show-grades {
            display: block;
            border: 0px;
            border-radius: 16px;
            margin: 10px;
        }

        .select {
            margin: 0px;
        }

        .calendar-header {
            font-size: 18px !important;
        }
    }

    ");

WriteLiteral("@media(max-width:450px) {\r\n       /* h2 {\r\n            font-size: 1em;\r\n        }" +
"*/\r\n    }\r\n</style>\r\n\r\n\r\n\r\n<section");

WriteLiteral(" class=\"page-banner\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"page-title-wrapper\"");

WriteLiteral(">\r\n            <div>\r\n                <ul");

WriteLiteral(" class=\"bradcurmed\"");

WriteLiteral(">\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5059), Tuple.Create("\"", 5099)
            
            #line 274 "..\..\Views\ToDoList\View.cshtml"
, Tuple.Create(Tuple.Create("", 5066), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dashboard")
            
            #line default
            #line hidden
, 5066), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 274 "..\..\Views\ToDoList\View.cshtml"
                                                                                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DashboardTitle")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5231), Tuple.Create("\"", 5270)
            
            #line 275 "..\..\Views\ToDoList\View.cshtml"
, Tuple.Create(Tuple.Create("", 5238), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "ToDoList")
            
            #line default
            #line hidden
, 5238), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 275 "..\..\Views\ToDoList\View.cshtml"
                                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "ToDoPageTitle1")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                </ul>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row m--margin-top-20-desktop\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-1 m-auto m--hidden-tablet m--hidden-mobile\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                    ");

            
            #line 281 "..\..\Views\ToDoList\View.cshtml"
               Write(Html.Partial("~/Views/SharedSvgs/_AssignmentsIcon.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-5 col-12 m-auto\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">");

            
            #line 285 "..\..\Views\ToDoList\View.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "ToDoPageTitle1")));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-3  m-auto\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-3 col-12 m-auto\"");

WriteLiteral(">\r\n\r\n\r\n                </div>\r\n            </div>\r\n\r\n\r\n        </div>\r\n\r\n\r\n    </" +
"div>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"page-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"row m-auto\"");

WriteLiteral(" dir=\"ltr\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"upper-part col-xl-12 col-lg-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 307 "..\..\Views\ToDoList\View.cshtml"
           Write(Html.Partial("_UpperPartPartialTest", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n</section>\r\n\r\n\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 319 "..\..\Views\ToDoList\View.cshtml"
Write(Scripts.Render("~/assets/vendors/select2/dist/js/select2.full.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    $(\"#footer\").remove();\r\n    $(\'.RenderBody\').removeClass(\'col-lg-" +
"9 col-md-9\');\r\n    $(\'.RenderBody\').prev().remove();\r\n        $(\".m-portlet__nav" +
"\").hide();\r\n    $(document).on(\'click\', \'.show-grades\', function () {\r\n        i" +
"f ($(this).text() === \"Show filters\") {\r\n            $(this).text(\"Hide filters\"" +
");\r\n        }\r\n        else {\r\n            $(this).text(\"Show filters\");\r\n      " +
"  }\r\n        $(\".m-accordion\").toggle();\r\n    })\r\n\r\n    var grade = \"-1\";\r\n\r\n   " +
" $(document).on(\'click\', \'.gradeBtn\', function () {\r\n        var btns = $(\'.grad" +
"eBtn\');\r\n\r\n        for (var i = 0; i < btns.length; i++) {\r\n            if ($(bt" +
"ns[i]).data(\'filter\') === \"all\") {\r\n                $(this).css(\'color\', \'white\'" +
");\r\n                $(this).css(\'background\', \'#2b2350\');\r\n                for (" +
"var j = i+1; j < btns.length; j++) {\r\n\r\n                    $(btns[j]).css(\'colo" +
"r\', \'#2b2350\');\r\n                    $(btns[j]).css(\'background\', \'#fff\');\r\n    " +
"            }\r\n            }\r\n            else {\r\n                $(btns[0]).css" +
"(\'color\', \'#2b2350\');\r\n                $(btns[0]).css(\'background\', \'#fff\');\r\n  " +
"              $(this).css(\'color\', \'white\');\r\n                $(this).css(\'backg" +
"round\', \'#2b2350\');\r\n            }\r\n        }\r\n\r\n        grade = $(this).data(\'i" +
"d\');\r\n       // Search();\r\n    })\r\n\r\n    var items = $(\".item-todo\");\r\n    if (i" +
"tems.length != 0) {\r\n        $(items[items.length - 1]).addClass(\"no-border\");\r\n" +
"\r\n    }\r\n        $(\"#searchInput\").parent().parent().remove();\r\n    //searchInpu" +
"t change\r\n    $(document).on(\'input\', \'.searchInput\', function () {\r\n        if " +
"($(\".searchInput\").val().length >= 3 || $(\".searchInput\").val().length == 0) {\r\n" +
"            setTimeout(function () { Search() }, 2000);\r\n            // Search()" +
"\r\n            $(\".info-error-container\").css(\'display\', \'none\');\r\n        }\r\n   " +
"     else {\r\n            $(\".info-error-container\").css(\'display\', \'block\');\r\n  " +
"      }\r\n    })\r\n\r\n        $(document).on(\'focusout\', \'.searchInput\', function (" +
") {\r\n                $(\".info-error-container\").css(\'display\', \'none\');\r\n\r\n     " +
"   })\r\n\r\n        //search call function\r\n        function Search() {\r\n          " +
"  mApp.block(\'.todos-container\');\r\n            var querySearch = $(\".searchInput" +
"\").val();\r\n            var dateSent = $(\"#dateText\").text();\r\n            $.ajax" +
"({\r\n                url: \'");

            
            #line 391 "..\..\Views\ToDoList\View.cshtml"
                 Write(Url.Action("SearchView"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"POST\",\r\n                dataType: \"html\",\r\n           " +
"     data: {\r\n                    query: querySearch,\r\n                    date:" +
" dateSent,\r\n                    sstgKey: \'");

            
            #line 397 "..\..\Views\ToDoList\View.cshtml"
                         Write(ViewBag.SSTGKey);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                    __RequestVerificationToken: $(\'");

            
            #line 398 "..\..\Views\ToDoList\View.cshtml"
                                              Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral(@"').val()
                },
                success: function (response) {

                    mApp.unblock('.todos-container');
                    $("".todos-container"").empty();
                    $("".todos-container"").html(response);
                    var items = $("".item-todo"");
                    if (items.length != 0) {
                        $(items[items.length - 1]).addClass(""no-border"");

                    }

                },
                error: function () {
                    mApp.unblock('.todos-container');
                    swal(""Something Went Wrong!"", ""We couldn't filter your sessions, please try again later."", ""error"");
                }
            })
        }




        //Date Manipulation (Prev)
    $(document).on('click', '.previousDayBtn', function () {
            grade = ""-1"";
            mApp.block("".todos-container"");
            var dateSent = $(""#dateText"").text();
             $.ajax({
                url: '");

            
            #line 428 "..\..\Views\ToDoList\View.cshtml"
                 Write(Url.Action("DateManipulationView"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"POST\",\r\n                dataType: \"html\",\r\n           " +
"      data: {\r\n                     optionNeeded: \"prev\",\r\n                     " +
"date: dateSent,\r\n                     SSTGKey: \'");

            
            #line 434 "..\..\Views\ToDoList\View.cshtml"
                          Write(ViewBag.SSTGKey);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                     __RequestVerificationToken: $(\'");

            
            #line 435 "..\..\Views\ToDoList\View.cshtml"
                                               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral(@"').val()
                 },
                 success: function (response) {
                     mApp.unblock("".todos-container"");
                     $("".upper-part"").empty();
                     $("".upper-part"").html(response);
                     var items = $("".item-todo"");
                     if (items.length != 0) {
                         $(items[items.length - 1]).addClass(""no-border"");

                     }
                     initRefreshCalendar();
                     $("".m-portlet__nav"").hide();
                    },
                error: function () {
                    swal(""Something Went Wrong!"", ""We couldn't filter your sessions, please try again later."", ""error"");
                }
            })
        })

        //DateManipulation (Next)
    $(document).on('click', '.nextDayBtn', function () {
            grade = ""-1"";
            var dateSent = $(""#dateText"").text();
            mApp.block("".todos-container"");

           $.ajax({
                url: '");

            
            #line 462 "..\..\Views\ToDoList\View.cshtml"
                 Write(Url.Action("DateManipulationView"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"POST\",\r\n                dataType: \"html\",\r\n           " +
"    data: {\r\n                   optionNeeded: \"next\",\r\n                   date: " +
"dateSent,\r\n                   SSTGKey: \'");

            
            #line 468 "..\..\Views\ToDoList\View.cshtml"
                        Write(ViewBag.SSTGKey);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                   __RequestVerificationToken: $(\'");

            
            #line 469 "..\..\Views\ToDoList\View.cshtml"
                                             Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\').val()\r\n               },\r\n               success: function (response) {\r\n     " +
"              $(\".upper-part\").empty();\r\n                   $(\".upper-part\").htm" +
"l(response);\r\n                   var items = $(\".item-todo\");\r\n                 " +
"  if (items.length != 0) {\r\n                       $(items[items.length - 1]).ad" +
"dClass(\"no-border\");\r\n\r\n                   }\r\n                   mApp.unblock(\"." +
"container\");\r\n                   initRefreshCalendar();\r\n                   $(\"." +
"m-portlet__nav\").hide();\r\n                    },\r\n               error: function" +
" () {\r\n                   mApp.unblock(\".todos-container\");\r\n                   " +
" swal(\"Something Went Wrong!\", \"We couldn\'t filter your sessions, please try aga" +
"in later.\", \"error\");\r\n                }\r\n            })\r\n       })\r\n\r\n\r\n\r\n\r\n   " +
"     //Calendar\r\n        const month_names = [\'January\', \'February\', \'March\', \'A" +
"pril\', \'May\', \'June\', \'July\', \'August\', \'September\', \'October\', \'November\', \'Dec" +
"ember\']\r\n        var currDate = new Date()\r\n        var curr_month = { value: cu" +
"rrDate.getMonth() }\r\n    var curr_year = { value: currDate.getFullYear() }\r\n\r\n  " +
"  $(document).ready(function () {\r\n        generateCalendar(curr_month.value, cu" +
"rr_year.value);\r\n\r\n    })\r\n\r\n    function initRefreshCalendar() {\r\n\r\n\r\n        l" +
"et calendar = document.querySelector(\'.calendar\');\r\n\r\n        let month_list = $" +
"(\'.month-list\')\r\n\r\n        generateCalendar(curr_month.value, curr_year.value)\r\n" +
"\r\n    }\r\n    $(document).on(\'click\', \'.month-list > div\', function () {\r\n\r\n     " +
"       $(\".month-list\").removeClass(\'show\')\r\n            $(\".calendar-header\").c" +
"ss(\"visibility\", \"visible\")\r\n            $(\".calendar-body\").css(\"visibility\", \"" +
"visible\")\r\n            curr_month.value = $(this).attr(\'data-month\')\r\n          " +
"  generateCalendar(curr_month.value, curr_year.value)\r\n\r\n\r\n    })\r\n\r\n    functio" +
"n checkifExist(arr, elem) {\r\n        for (var i = 0; i < arr.length; i++) {\r\n   " +
"         if (arr[i] === elem) return true;\r\n        }\r\n        return false;\r\n  " +
"  }\r\n        isLeapYear = (year) => {\r\n            return (year % 4 === 0 && yea" +
"r % 100 !== 0 && year % 400 !== 0) || (year % 100 === 0 && year % 400 === 0)\r\n  " +
"      }\r\n\r\n        getFebDays = (year) => {\r\n            return isLeapYear(year)" +
" ? 29 : 28\r\n    }\r\n\r\n\r\n\r\n        var days_of_month = [31, getFebDays(year), 31, " +
"30, 31, 30, 31, 31, 30, 31, 30, 31]\r\n\r\n    function generateCalendar(month, year" +
") {\r\n        let calendar_days = $(\'.calendar-days\')\r\n        let calendar_heade" +
"r_year = $(\'#year\')\r\n\r\n\r\n\r\n        calendar_days.empty();\r\n        //calendar_da" +
"ys.innerHTML = \'\'\r\n\r\n\r\n        let currDate = new Date()\r\n\r\n        let curr_mon" +
"th = `${month_names[month]}`\r\n\r\n\r\n\r\n        $(\"#month-picker\").empty()\r\n        " +
"$(\"#month-picker\").text(curr_month)\r\n        //month_picker.innerHTML = curr_mon" +
"th\r\n\r\n        calendar_header_year.empty()\r\n        calendar_header_year.append(" +
"year)\r\n\r\n        // calendar_header_year.innerHTML = year\r\n\r\n        // get firs" +
"t day of month\r\n\r\n        let first_day = new Date(year, month, 1)\r\n\r\n\r\n        " +
"//Test AJAX days\r\n        var dateToSend = month_names[month] + \" \" + year;\r\n\r\n " +
"       console.log(\"dateToSenddateToSend\");\r\n        console.log(dateToSend);\r\n " +
"           $.ajax({\r\n                url: \'");

            
            #line 579 "..\..\Views\ToDoList\View.cshtml"
                 Write(Url.Action("DaysManipulationView","ToDoList"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"POST\",\r\n                dataType: \"json\",\r\n           " +
"    data: {\r\n                   date: dateToSend,\r\n                   sstgKey: \'" +
"");

            
            #line 584 "..\..\Views\ToDoList\View.cshtml"
                        Write(ViewBag.SSTGKey);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                   __RequestVerificationToken: $(\'");

            
            #line 585 "..\..\Views\ToDoList\View.cshtml"
                                             Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\').val()\r\n                },\r\n                success: function (response) {\r\n   " +
"                 console.log(\"la2atik1233\");\r\n                    console.log(re" +
"sponse);\r\n                        mApp.unblock(\".calendar-body\");\r\n             " +
"            for (let i = 0; i <= days_of_month[month] + first_day.getDay() - 1; " +
"i++) {\r\n\r\n                           let day = document.createElement(\'div\')\r\n  " +
"                         if (i >= first_day.getDay()) {\r\n                       " +
"        day.classList.add(\'calendar-day-hover\')\r\n                               " +
"day.innerHTML = i - first_day.getDay() + 1\r\n                               //hon" +
"e i get the date\r\n\r\n                               var dayToCheck = i - first_da" +
"y.getDay() + 1+\"\";\r\n                               if (checkifExist(response, da" +
"yToCheck)) {\r\n                                   day.classList.add(\'day-work\');\r" +
"\n                               }\r\n\r\n\r\n                               if (i - fi" +
"rst_day.getDay() + 1 === currDate.getDate() && year === currDate.getFullYear() &" +
"& month === currDate.getMonth()) {\r\n                                   day.class" +
"List.add(\'curr-date\')\r\n                               }\r\n\r\n                     " +
"        }\r\n\r\n                           calendar_days.append(day)\r\n             " +
"              //calendar_days.appendChild(day)\r\n                       }\r\n\r\n    " +
"                    },\r\n                error: function (err) {\r\n               " +
"     console.log(\"la2atik\");\r\n                    console.log(err);\r\n           " +
"         swal(\"Something Went Wrong!!!123\", \"We couldn\'t filter your sessions, p" +
"lease try again later.\", \"error\");\r\n                }\r\n            })\r\n\r\n\r\n\r\n   " +
" }\r\n\r\n\r\n\r\n\r\n\r\n        let month_picker = $(\'#month-picker\')\r\n\r\n    $(document).o" +
"n(\'click\', \'#month-picker\', function () {\r\n        let month_list = $(\'.month-li" +
"st\')\r\n            month_list.addClass(\'show\')\r\n            $(\".calendar-header\")" +
".css(\"visibility\", \"hidden\")\r\n            $(\".calendar-body\").css(\"visibility\", " +
"\"hidden\")\r\n        })\r\n\r\n\r\n\r\n\r\n\r\n        $(document).on(\'click\', \'#prev-year\', f" +
"unction () {\r\n            --curr_year.value\r\n            generateCalendar(curr_m" +
"onth.value, curr_year.value)\r\n        })\r\n\r\n        $(document).on(\'click\', \'#ne" +
"xt-year\', function () {\r\n            ++curr_year.value\r\n            generateCale" +
"ndar(curr_month.value, curr_year.value)\r\n        })\r\n\r\n\r\n\r\n    $(document).on(\'c" +
"lick\', \'.day-work\', function () {\r\n            grade = \"-1\";\r\n            $(\".ca" +
"lendar\").toggle();\r\n            var day = $(this).text();\r\n            var month" +
" = $(\"#month-picker\").text();\r\n            var year = $(\"#year\").text();\r\n      " +
"      var dateToSend = day + \" \" + month + \" \" + year;\r\n\r\n            mApp.block" +
"(\".todos-container\");\r\n\r\n           $.ajax({\r\n                url: \'");

            
            #line 667 "..\..\Views\ToDoList\View.cshtml"
                 Write(Url.Action("DateManipulationView"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"POST\",\r\n                dataType: \"html\",\r\n           " +
"    data: {\r\n                   optionNeeded: \"none\",\r\n                   date: " +
"dateToSend,\r\n                   SSTGKey: \'");

            
            #line 673 "..\..\Views\ToDoList\View.cshtml"
                        Write(ViewBag.SSTGKey);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                   __RequestVerificationToken: $(\'");

            
            #line 674 "..\..\Views\ToDoList\View.cshtml"
                                             Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\').val()\r\n               },\r\n               success: function (response) {\r\n     " +
"              $(\".upper-part\").empty();\r\n                   $(\".upper-part\").htm" +
"l(response);\r\n                   mApp.unblock(\".container\");\r\n                  " +
" initRefreshCalendar();\r\n                   var items = $(\".item-todo\");\r\n      " +
"             if (items.length != 0) {\r\n                       $(items[items.leng" +
"th - 1]).addClass(\"no-border\");\r\n\r\n                   }\r\n                   $(\"." +
"m-portlet__nav\").hide();\r\n                    },\r\n               error: function" +
" () {\r\n                   mApp.unblock(\".todos-container\");\r\n                   " +
" swal(\"Something Went Wrong!\", \"We couldn\'t filter your sessions, please try aga" +
"in later.\", \"error\");\r\n                }\r\n            })\r\n\r\n        })\r\n\r\n\r\n\r\n\r\n" +
"        var month = \"January\";\r\n        var index = 0;\r\n\r\n        $(document).on" +
"(\'click\', \'#prev-year-mobile\', function () {\r\n            var oldYear = $(\"#year" +
"-mobile\").text();\r\n            var newYear = parseInt(oldYear) != NaN ? parseInt" +
"(oldYear) - 1 : oldYear;\r\n            $(\"#year-mobile\").text(newYear);\r\n\r\n      " +
"  })\r\n        $(document).on(\'click\', \'#next-year-mobile\', function () {\r\n      " +
"      var oldYear = $(\"#year-mobile\").text();\r\n            var newYear = parseIn" +
"t(oldYear) != NaN ? parseInt(oldYear) + 1 : oldYear;\r\n            $(\"#year-mobil" +
"e\").text(newYear);\r\n        })\r\n\r\n        $(document).on(\'change\', \"#month-selec" +
"t2\", function () {\r\n            $(\"#day-mobile\").text(\"1\");\r\n           var mont" +
"hSelected = $(\"#month-select2 option:selected\").val();\r\n            for (var i =" +
" 0; i < month_names.length; i++) {\r\n                if (monthSelected === month_" +
"names[i]) {\r\n                    month = month_names[i];\r\n                    in" +
"dex = i;\r\n                }\r\n            }\r\n\r\n        })\r\n\r\n        //Mobile day" +
"s\r\n\r\n        $(document).on(\'click\', \'#prev-day-mobile\', function () {\r\n        " +
"    var oldDay = $(\"#day-mobile\").text();\r\n            var newDay = parseInt(old" +
"Day) > 1 ? parseInt(oldDay) - 1 : 1;\r\n           $(\"#day-mobile\").text(newDay);\r" +
"\n\r\n        })\r\n\r\n\r\n\r\n        $(document).on(\'click\', \'#next-day-mobile\', functio" +
"n () {\r\n\r\n            var oldDay = $(\"#day-mobile\").text();\r\n            var max" +
"Days = parseInt(days_of_month[index]);\r\n            var newDay = 0;\r\n           " +
"  newDay = parseInt(oldDay) < maxDays ? parseInt(oldDay) + 1 : maxDays;\r\n       " +
"       $(\"#day-mobile\").text(newDay);\r\n\r\n        })\r\n\r\n\r\n\r\n        //select2\r\n\r\n" +
"        $(\"#month-select2\").select2({ placeholder: \"Select a Month\" })\r\n\r\n\r\n\r\n\r\n" +
"        $(document).on(\'click\', \"#go-mobile\", function () {\r\n            $(\".cal" +
"endar\").toggle();\r\n            var day = $(\"#day-mobile\").text();\r\n            v" +
"ar month = $(\"#month-select2 option:selected\").val();\r\n            var year = $(" +
"\"#year-mobile\").text();\r\n            var dateToSend = day + \" \" + month + \" \" + " +
"year;\r\n\r\n            mApp.block(\".todos-container\");\r\n\r\n           $.ajax({\r\n   " +
"             url: \'");

            
            #line 766 "..\..\Views\ToDoList\View.cshtml"
                 Write(Url.Action("DateManipulationView"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"POST\",\r\n                dataType: \"html\",\r\n           " +
"    data: {\r\n                   optionNeeded: \"none\",\r\n                   date: " +
"dateToSend,\r\n                   SSTGKey: \'");

            
            #line 772 "..\..\Views\ToDoList\View.cshtml"
                        Write(ViewBag.SSTGKey);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                   __RequestVerificationToken: $(\'");

            
            #line 773 "..\..\Views\ToDoList\View.cshtml"
                                             Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\').val()\r\n               },\r\n               success: function (response) {\r\n     " +
"              $(\".upper-part\").empty();\r\n                   $(\".upper-part\").htm" +
"l(response);\r\n                   mApp.unblock(\".container\");\r\n                  " +
" $(\"#day-mobile\").text(\"1\");\r\n                   $(\"#month-select2 option:select" +
"ed\").val(\"January\");\r\n                   grade = \"-1\";\r\n                   $(\"#y" +
"ear-mobile\").text(\"2022\");\r\n                   initRefreshCalendar();\r\n         " +
"          $(\".m-portlet__nav\").hide();\r\n                    },\r\n               e" +
"rror: function () {\r\n                   mApp.unblock(\".todos-container\");\r\n     " +
"               swal(\"Something Went Wrong!\", \"We couldn\'t filter your sessions, " +
"please try again later.\", \"error\");\r\n                }\r\n            })\r\n        " +
"})\r\n\r\n    $(document).on(\'click\', document, function (e) {\r\n        var targets " +
"= [\'dateText\', \'calendar\',\'prev-year-mobile\',\'select2-month-select2-container\',\'" +
"next-year-mobile\',\'month-select2\',\'select2\', \'calendar-header\', \'calendar-body\'," +
" \'year\', \'month-picker\', \'month\',\'arrows\',\'prev-year\',\'next-year\'];\r\n        for" +
" (var i = 0; i < targets.length; i++){\r\n            if (e.target.className === t" +
"argets[i] || e.target.id === targets[i]) {\r\n                $(\".calendar\").css(\"" +
"display\", \"block\");\r\n                if ($(\".calendar-days\").children().length==" +
"0) {\r\n\r\n                mApp.block(\".calendar-body\");\r\n                }\r\n      " +
"          break;\r\n            }\r\n            else {\r\n                $(\".calenda" +
"r\").css(\"display\", \"none\");\r\n            }\r\n    }\r\n\r\n    })\r\n\r\n        $(\"#foote" +
"r\").css(\'display\', \'none\');\r\n\r\n\r\n</script>\r\n\r\n\r\n\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
