#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\WhatsToday\Index.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\WhatsToday\Index.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/WhatsToday/Index.cshtml")]
    public partial class _Views_WhatsToday_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_WhatsToday_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\WhatsToday\Index.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;
    List<RLI.EntityFramework.EDM.Assignment> todayAssignments = ViewBag.TodayAssignments;
    List<SynchronousSession> todaySessions = ViewBag.TodaySessions;
    List<Lesson> todayLessons = ViewBag.TodayLessons;
    List<RLI.Common.DataObjects.MoodleEventViewModel> todayEvents = ViewBag.TodayEvents;
    ViewBag.Title = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_WhatsToday"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .page-banner {\r\n        margin-top: 100px;\r\n        height: fit-co" +
"ntent;\r\n        margin-bottom: 30px;\r\n        background-color: #ffffff;\r\n    }\r" +
"\n\r\n    .assignmentClass-1 {\r\n        fill: #292656 !important;\r\n    }\r\n\r\n    .as" +
"signmentClass-2 {\r\n        fill: #f3f3ff !important;\r\n    }\r\n\r\n    .assignmentCl" +
"ass-3 {\r\n        fill: #fc6930 !important;\r\n    }\r\n\r\n    .assignmentClass-4 {\r\n " +
"       fill: #f97735 !important;\r\n    }\r\n\r\n    .assignmentClass-5 {\r\n        fil" +
"l: #297f96 !important;\r\n    }\r\n\r\n    .assignmentClass-6 {\r\n        fill: #61c1c6" +
" !important;\r\n    }\r\n\r\n    .assignmentClass-7 {\r\n        fill: #2f90b2 !importan" +
"t;\r\n    }\r\n\r\n    .assignmentClass-8 {\r\n        fill: #7bf3ff !important;\r\n    }\r" +
"\n\r\n    .assignmentClass-9 {\r\n        fill: #41c3ff !important;\r\n    }\r\n\r\n    .as" +
"signmentClass-10 {\r\n        fill: url(#linear-gradient) !important;\r\n    }\r\n\r\n  " +
"  .assignmentClass-11 {\r\n        fill: url(#linear-gradient-assignment) !importa" +
"nt;\r\n    }\r\n</style>\r\n<style>\r\n\r\n    .whiteHover a {\r\n        color: #2b2350 !im" +
"portant;\r\n        font-size: 1.4rem;\r\n    }\r\n\r\n        .whiteHover a:hover {\r\n  " +
"          color: #fff !important;\r\n        }\r\n\r\n    .m-widget3__info {\r\n        " +
"line-height: 20px !important;\r\n    }\r\n\r\n    .bookmarkContainer {\r\n        displa" +
"y: block;\r\n        position: absolute;\r\n        left: 0;\r\n        text-align: en" +
"d;\r\n        top: 45px;\r\n    }\r\n\r\n        .bookmarkContainer i {\r\n            col" +
"or: #2b2350;\r\n        }\r\n\r\n    .m-dropdown__inner {\r\n        width: 90%;\r\n    }\r" +
"\n\r\n    .m-portlet .m-portlet__head {\r\n        border-bottom: unset !important;\r\n" +
"    }\r\n\r\n    .post-post-grid {\r\n        overflow: unset !important;\r\n    }\r\n\r\n  " +
"  .m-widget3__user-img svg {\r\n        width: 3.2rem;\r\n    }\r\n\r\n    .m-widget3__b" +
"ody h3 {\r\n        font-size: 1.4rem;\r\n    }\r\n\r\n    .m-portlet {\r\n        backgro" +
"und-color: transparent !important;\r\n    }\r\n\r\n        .m-portlet .m-portlet__head" +
" .m-portlet__head-text {\r\n            color: #2b2350;\r\n        }\r\n\r\n    .la-elli" +
"psis-h {\r\n        color: #292656;\r\n    }\r\n\r\n    ");

WriteLiteral("@media(max-width:991px) {\r\n        .BodyParent #m_aside_left {\r\n            displ" +
"ay: none !important;\r\n        }\r\n\r\n        .messgIcon {\r\n            display: no" +
"ne;\r\n        }\r\n    }\r\n</style>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <section");

WriteLiteral(" class=\"page-banner\"");

WriteLiteral(" style=\"height:auto\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"page-title-wrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"mt-3\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"bradcurmed\"");

WriteLiteral(">\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3398), Tuple.Create("\"", 3438)
            
            #line 153 "..\..\Views\WhatsToday\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3405), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dashboard")
            
            #line default
            #line hidden
, 3405), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 153 "..\..\Views\WhatsToday\Index.cshtml"
                                                                                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Wall")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3561), Tuple.Create("\"", 3602)
            
            #line 154 "..\..\Views\WhatsToday\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3568), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "WhatsToday")
            
            #line default
            #line hidden
, 3568), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 154 "..\..\Views\WhatsToday\Index.cshtml"
                                                                                          Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_WhatsToday")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n\r\n        <" +
"div");

WriteLiteral(" class=\"row m--margin-top-20-desktop\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-1 m-auto messgIcon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"m-menu__link-icon fa fa-calendar-check mr-2\"");

WriteLiteral(" style=\"font-size: 3.5rem; color: #2b2350\"");

WriteLiteral("></i>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-5 col-12 m-auto\"");

WriteLiteral(">\r\n                <h1");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">");

            
            #line 164 "..\..\Views\WhatsToday\Index.cshtml"
                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_WhatsToday")));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-3  m-auto\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-3 col-12 m-auto\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n    </section>\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"row m--margin-top-50\"");

WriteLiteral(" style=\"overflow-y:hidden !important;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-12 contents\"");

WriteLiteral(">\r\n                <article");

WriteLiteral(" class=\"post-post-grid\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-portlet m-portlet--full-height \"");

WriteLiteral(" style=\"margin:0\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-portlet__head\"");

WriteLiteral(" style=\"height:100%\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-portlet__body row\"");

WriteLiteral(" style=\"padding:25px;\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"m-widget3\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"m-widget3__item\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 189 "..\..\Views\WhatsToday\Index.cshtml"
                                   Write(Html.Partial("_WhatsTodaySideMenu", new Lesson(), new ViewDataDictionary { { "Locale", Locale }, { "todayAssignments", todayAssignments }, { "todaySessions", todaySessions }, { "todayEvents", todayEvents }, { "todayLessons", todayLessons } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        ");

WriteLiteral(@"
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </article>
            </div>
        </div>
        
    </div>
</div>
");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 222 "..\..\Views\WhatsToday\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 223 "..\..\Views\WhatsToday\Index.cshtml"
Write(Scripts.Render("~/assets/vendors/select2/dist/js/select2.full.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--Reference the SignalR library. -->\r\n");

WriteLiteral("    ");

            
            #line 226 "..\..\Views\WhatsToday\Index.cshtml"
Write(Scripts.RenderFormat("<script src='https://" + Request.Url.Host + "/{0}'></script>", "~/Scripts/jquery.signalR-2.4.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--Reference the autogenerated SignalR hub script. -->\r\n");

WriteLiteral("    ");

            
            #line 228 "..\..\Views\WhatsToday\Index.cshtml"
Write(Scripts.RenderFormat("<script src='https://" + Request.Url.Host + "/{0}'></script>", "~/signalr/hubs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script>\r\n        $(document).ready(function () {\r\n            $(\'.Render" +
"Body\').removeClass(\'col-md-9\');\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
