#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PresentialSessions/_presentialSessionSelectAudience.cshtml")]
    public partial class _Views_PresentialSessions__presentialSessionSelectAudience_cshtml : System.Web.Mvc.WebViewPage<RLI.WebApplication.Models.SynchronousSessionSelectAudienceViewModel>
    {
        public _Views_PresentialSessions__presentialSessionSelectAudience_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
 using (Html.BeginForm("SessionSelectAudience", "PresentialSessions", FormMethod.Post, new { @class = "m-form m-form--label-align-left", @id = "sessionSelectedAudienceForm", role = "form", novalidate = "novalidate" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-1 col-12\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"col-md-10 col-12\"");

WriteLiteral(">\r\n            <!-- to move to partial -->\r\n            <div");

WriteLiteral(" class=\"m-form__heading\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"font-weight-bold\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageSelectAudienceTitle")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h3>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"mt-5\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                 if (RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name == "Student" && ViewBag.ClassTeacher != null)
                {
                    Teacher ClassTeacher = ViewBag.ClassTeacher;

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-4 col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 27 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageSelectTeacherAudience")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-8 col-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" id=\"enrolled_students\"");

WriteLiteral(" style=\"min-height:100px\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <ul>\r\n                                    <li>\r" +
"\n                                        <label");

WriteLiteral(" class=\"m-checkbox\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" class=\"teacher\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"selectTeacher\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2068), Tuple.Create("\"", 2100)
            
            #line 38 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                               , Tuple.Create(Tuple.Create("", 2076), Tuple.Create<System.Object, System.Int32>(ClassTeacher.TeacherKey
            
            #line default
            #line hidden
, 2076), false)
);

WriteLiteral(" checked=\"checked\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                                                                                                                                      Write(ClassTeacher.FirstName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 38 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                                                                                                                                                              Write(ClassTeacher.LastName);

            
            #line default
            #line hidden
WriteLiteral(@"
                                            <span></span>
                                        </label>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
");

            
            #line 46 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-4 col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                   Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageSelectAudience")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"enrolled_students\"");

WriteLiteral(" style=\"min-height:100px\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"m-checkbox m-checkbox--air\"");

WriteLiteral(">\r\n                                All<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"all_students\"");

WriteLiteral(" data-child=\"students\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" />\r\n                                <span></span>\r\n                            <" +
"/label>\r\n\r\n                            <ul>\r\n");

            
            #line 60 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                 foreach (var student in Model.StudentsEnrolled)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <label");

WriteLiteral(" class=\"m-checkbox\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" class=\"student\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"studentsSelected\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3485), Tuple.Create("\"", 3512)
            
            #line 64 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                  , Tuple.Create(Tuple.Create("", 3493), Tuple.Create<System.Object, System.Int32>(student.StudentKey
            
            #line default
            #line hidden
, 3493), false)
);

WriteLiteral(" checked=\"checked\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                                                                                                                                    Write(student.StudentName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <span></span>\r\n                    " +
"                    </label>\r\n                                    </li>\r\n");

            
            #line 68 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </div>\r\n              " +
"      </div>\r\n                </div>\r\n\r\n            </div>\r\n        </div>\r\n    " +
"    <div");

WriteLiteral(" class=\"col-md-1 col-12\"");

WriteLiteral("></div>\r\n    </div>\r\n");

            
            #line 78 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<script>\r\n     //initiale all the function for the select audience in Edit " +
"Page\r\n                nbStudentChecked = \'");

            
            #line 85 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                               Write(Model.SelectedStudentsEnrolled.Count());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n                var numberOfStudents = \'");

            
            #line 86 "..\..\Views\PresentialSessions\_presentialSessionSelectAudience.cshtml"
                                   Write(Model.StudentsEnrolled.Count());

            
            #line default
            #line hidden
WriteLiteral(@"';
                $('.student').change(function () {
                    if ($(this).is("":checked"")) {
                        nbStudentChecked++;
                        if (nbStudentChecked == numberOfStudents) {
                            $('.all_students').prop('checked', true);
                        }
                    } else {
                        nbStudentChecked--;
                        $('.all_students').prop('checked', false);
                    }
                });
                $('.all_students').change(function () {
                    if ($(this).is("":checked"")) {
                        $('.student').prop('checked', true);
                        nbStudentChecked = numberOfStudents;
                    } else {
                        $('.student').prop('checked', false);
                        nbStudentChecked = 0;
                    }
                });
                if (nbStudentChecked == 0) {
                    $('.all_students').click();
                }
</script>


");

        }
    }
}
#pragma warning restore 1591
