#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PresentialSessions/_PresentialSessionSetup.cshtml")]
    public partial class _Views_PresentialSessions__PresentialSessionSetup_cshtml : System.Web.Mvc.WebViewPage<RLI.WebApplication.Models.SynchronousSessionsSetupViewModel>
    {
        public _Views_PresentialSessions__PresentialSessionSetup_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
 using (Html.BeginForm("SessionSetup", "PresentialSessions", FormMethod.Post, new { @class = "m-form m-form--label-align-left", @id = "sessionSetupForm", role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"m-form__heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"font-weight-bold\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSessionDetails")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </h3>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"m-form__content\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary m-auto\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateTopic")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                  string topic = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control m-input m-auto", @placeholder = @Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateWhatIsAbout?")) } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.ValidationMessageFor(model => model.Topic, topic, new { @class = "validationMssg text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary m--margin-top-5\"");

WriteLiteral(">");

            
            #line 29 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                                                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateDescription")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                  string desc = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.TextAreaFor(model => model.Descriprion, new { @class = "form-control m-input w-100 m-auto", @placeholder = @Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateTellYourAudienceMoreAboutIt..")), @rows = "5" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.ValidationMessageFor(model => model.Descriprion, desc, new { @class = "validationMssg text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary m-auto\"");

WriteLiteral(">");

            
            #line 37 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSessionDate")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"SessionDateTime\"");

WriteLiteral(" name=\"SessionDateTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control m-input m-auto\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2879), Tuple.Create("\"", 2992)
            
            #line 39 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                                                , Tuple.Create(Tuple.Create("", 2893), Tuple.Create<System.Object, System.Int32>(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateWhenIsTheSession?"))
            
            #line default
            #line hidden
, 2893), false)
);

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n");

            
            #line 40 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                  string date = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.HiddenFor(model => model.SessionDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.ValidationMessageFor(model => model.SessionDate, date, new { @class = "validationMssg text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary m-auto\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateDuration")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 48 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
                  string duration = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                <input");

WriteLiteral(" id=\"MeetingDuration\"");

WriteLiteral(" name=\"MeetingDuration\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" class=\"form-control m-input m-auto\"");

WriteLiteral(" placeholder=\"How long?\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
           Write(Html.ValidationMessageFor(model => model.MeetingDuration, duration, new { @class = "validationMssg text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 54 "..\..\Views\PresentialSessions\_PresentialSessionSetup.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
