#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 2 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
    using RLI.EntityFramework.EDM;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PresentialSessions/_PresentialSessionsGrid.cshtml")]
    public partial class _Views_PresentialSessions__PresentialSessionsGrid_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<RLI.EntityFramework.EDM.SynchronousSession>>
    {
        public _Views_PresentialSessions__PresentialSessionsGrid_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;
    int CurrentLanguageIdentifier = (int)ViewBag.CurrentLanguageIdentifier;
    AspNetUser CurrentUser = ViewBag.CurrentUser;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .m-dropdown__wrapper {\r\n        top: -200px !important;\r\n    }\r\n</" +
"style>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 432), Tuple.Create("\"", 519)
            
            #line 16 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
, Tuple.Create(Tuple.Create("", 440), Tuple.Create<System.Object, System.Int32>(Model == null || Model.Count() == 0 ? "" : "d-none"
            
            #line default
            #line hidden
, 440), false)
, Tuple.Create(Tuple.Create(" ", 494), Tuple.Create("blankslate", 495), true)
, Tuple.Create(Tuple.Create(" ", 505), Tuple.Create("m-auto", 506), true)
, Tuple.Create(Tuple.Create(" ", 512), Tuple.Create("col-12", 513), true)
);

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
         if (RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name=="Teacher" || RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name == "Student")
        {
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
       Write(Html.Partial("_EmptySlateContainer", new ViewDataDictionary {
                       { "title", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_EmptySlateTitle")).ToString() },
                       { "subTitle",Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "Youdontseemtohaveanysessionsscheduled")).ToString() }
                       , { "description", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SchedulingasessionwillallowyoutoarrangeaVirtualClasswithyourstudents")).ToString() }
                       , { "action", true },
                       { "actionBtnId", "createSessionButtonEmptySlateBtn" },
                       { "actionBtnText", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSession")).ToString() } }));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                                                                                  
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
       Write(Html.Partial("_EmptySlateContainer", new ViewDataDictionary {
                        { "title", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_EmptySlateTitle")).ToString() },
                        { "subTitle",Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "Youdontseemtohaveanysessionsscheduled")).ToString() }
                        , { "description", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SchedulingasessionwillallowyoutoarrangeaVirtualClasswithyourstudents")).ToString() }
                        , { "action", false },
                        { "actionBtnId", "" },
                        { "actionBtnText", "" } }));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                  
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n    </div>\r\n\r\n");

            
            #line 53 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
     foreach (var item in Model)
    {



            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteAttribute("id", Tuple.Create(" id=\"", 3339), Tuple.Create("\"", 3376)
, Tuple.Create(Tuple.Create("", 3344), Tuple.Create("card-", 3344), true)
            
            #line 57 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
, Tuple.Create(Tuple.Create("", 3349), Tuple.Create<System.Object, System.Int32>(item.SynchronousSessionKey
            
            #line default
            #line hidden
, 3349), false)
);

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-12 mt-2 mb-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"grid-card\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-3 m--hidden-tablet-and-mobile\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 61 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                   Write(Html.Partial("~/Views/SharedSvgs/_SynchronousLearningIcon.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-lg-8 col-10\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m--font-primary\"");

WriteLiteral(">\r\n");

            
            #line 65 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                              
                                string gradeValue = CurrentLanguageIdentifier == 0 ? item.SchoolSubjectTeacherGrade.Grade.Grade1 : item.SchoolSubjectTeacherGrade.Grade.DataGUID.DataTranslations.Where(dt => dt.LanguageKey == CurrentLanguageIdentifier).FirstOrDefault().Value;
                                string subjectValue = CurrentLanguageIdentifier == 0 ? item.SchoolSubjectTeacherGrade.Subject.Subject1 : item.SchoolSubjectTeacherGrade.Subject.DataGUID.DataTranslations.Where(dt => dt.LanguageKey == CurrentLanguageIdentifier).FirstOrDefault().Value;
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 69 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                       Write(subjectValue);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"grid-card-head-title\"");

WriteLiteral(">\r\n                            <h3>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4623), Tuple.Create("\"", 4696)
, Tuple.Create(Tuple.Create("", 4630), Tuple.Create("javascript:GoogleDashboardSubmitForm(\'", 4630), true)
            
            #line 73 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
, Tuple.Create(Tuple.Create("", 4668), Tuple.Create<System.Object, System.Int32>(item.MeetingURL
            
            #line default
            #line hidden
, 4668), false)
, Tuple.Create(Tuple.Create("", 4684), Tuple.Create("?authuser=\')", 4684), true)
);

WriteLiteral(" ");

WriteLiteral(">");

            
            #line 73 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                                                            Write(item.Topic);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n                            </h3>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"grid-card-head-datetime\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-calendar fa-2x m--margin-right-10 align-middle m--font-brand d-inli" +
"ne-block\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"datetime align-middle text-secondary d-inline-block\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                         Write(item.SessionDate.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 79 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                                                                Write(item.SessionDate.ToString("hh:mm tt"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </div>\r\n                    </div>\r\n            " +
"        <div");

WriteLiteral(" class=\"col-lg-1 col-2\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" id=\"sessionUrlCopyButton\"");

WriteLiteral(" data-session-url=\"");

            
            #line 83 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                             Write(item.MeetingURL);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-copy fa-2x text-secondary\"");

WriteLiteral("></i>\r\n                        </a>\r\n                    </div>\r\n                " +
"</div>\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"grid-card-head-datetime col-6\"");

WriteLiteral(">\r\n\r\n                        <span");

WriteLiteral(" class=\"datetime align-middle text-secondary d-inline-block\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5754), Tuple.Create("\"", 5813)
, Tuple.Create(Tuple.Create("", 5759), Tuple.Create("latestSessionSpanElementId_", 5759), true)
            
            #line 92 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                         , Tuple.Create(Tuple.Create("", 5786), Tuple.Create<System.Object, System.Int32>(item.SynchronousSessionKey
            
            #line default
            #line hidden
, 5786), false)
);

WriteLiteral("></span>\r\n                    </div>\r\n\r\n\r\n                </div>\r\n               " +
" <div");

WriteLiteral(" class=\"grid-card-body m--font-primary\"");

WriteLiteral(">\r\n                    <p>\r\n");

WriteLiteral("                        ");

            
            #line 99 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                   Write(item.Descriprion);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n                </div>\r\n                ");

WriteLiteral("\r\n                <div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-12 m--font-primary\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 106 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                       Write(item.SchoolSubjectTeacherGrade.School.SchoolName);

            
            #line default
            #line hidden
WriteLiteral(" > ");

            
            #line 106 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                           Write(gradeValue);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n\r\n                    </div>\r\n\r\n               " +
"     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"text-align:end;\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"m-portlet__nav\"");

WriteLiteral(">\r\n                                <li");

WriteLiteral(" class=\"m-portlet__nav-item m-dropdown m-dropdown--inline m-dropdown--arrow m-dro" +
"pdown--align-right m-dropdown--align-push\"");

WriteLiteral(" m-dropdown-toggle=\"hover\"");

WriteLiteral(" aria-expanded=\"true\"");

WriteLiteral(">\r\n\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"m-portlet__nav-link m-portlet__nav-link--icon m-portlet__nav-link--icon-x" +
"l m-dropdown__toggle\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"la la-ellipsis-h m--font-primary\"");

WriteLiteral("></i>\r\n\r\n                                    </a>\r\n                              " +
"      <div");

WriteLiteral(" class=\"m-dropdown__wrapper\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust\"");

WriteLiteral("></span>\r\n                                        <div");

WriteLiteral(" class=\"m-dropdown__inner\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"m-dropdown__body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"m-dropdown__content\"");

WriteLiteral(">\r\n                                                    <ul");

WriteLiteral(" class=\"m-nav\"");

WriteLiteral(">\r\n\r\n                                                        <li");

WriteLiteral(" class=\"m-nav__item\"");

WriteLiteral(">\r\n                                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7708), Tuple.Create("\"", 7781)
, Tuple.Create(Tuple.Create("", 7715), Tuple.Create("javascript:GoogleDashboardSubmitForm(\'", 7715), true)
            
            #line 128 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                           , Tuple.Create(Tuple.Create("", 7753), Tuple.Create<System.Object, System.Int32>(item.MeetingURL
            
            #line default
            #line hidden
, 7753), false)
, Tuple.Create(Tuple.Create("", 7769), Tuple.Create("?authuser=\')", 7769), true)
);

WriteLiteral(" ");

WriteLiteral(" class=\"m-nav__link\">\r\n                                                          " +
"      <i");

WriteLiteral(" class=\"m-nav__link-icon fa fa-link\"");

WriteLiteral("></i>\r\n                                                                <span");

WriteLiteral(" class=\"m-nav__link-text\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                          Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Open")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                            </a>\r\n      " +
"                                                  </li>\r\n");

            
            #line 133 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                        
            
            #line default
            #line hidden
            
            #line 133 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                         if (CurrentUser.Id == item.CreatedByUserKey)
                                                        {

            
            #line default
            #line hidden
WriteLiteral("                                                            <li");

WriteLiteral(" class=\"m-nav__item\"");

WriteLiteral(">\r\n                                                                <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" data-session-id=\"");

            
            #line 136 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                                          Write(item.SynchronousSessionKey);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"deleteSessionButton m-nav__link\"");

WriteLiteral(">\r\n                                                                    <i");

WriteLiteral(" class=\"m-nav__link-icon fa fa-trash\"");

WriteLiteral("></i>\r\n                                                                    <span");

WriteLiteral(" class=\"m-nav__link-text\"");

WriteLiteral(">");

            
            #line 138 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageDelete")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                                </a>\r\n  " +
"                                                          </li>\r\n");

            
            #line 141 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                                                            <li");

WriteLiteral(" class=\"m-nav__item\"");

WriteLiteral(">\r\n                                                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 9250), Tuple.Create("\"", 9317)
            
            #line 143 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
, Tuple.Create(Tuple.Create("", 9257), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { id = item.SynchronousSessionKey })
            
            #line default
            #line hidden
, 9257), false)
);

WriteLiteral(" class=\"m-nav__link\"");

WriteLiteral(">\r\n                                                                    <i");

WriteLiteral(" class=\"m-nav__link-icon fa fa-edit\"");

WriteLiteral("></i>\r\n                                                                    <span");

WriteLiteral(" class=\"m-nav__link-text\"");

WriteLiteral(">");

            
            #line 145 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageEdit")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                                </a>\r\n  " +
"                                                          </li>\r\n");

            
            #line 148 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"

                                                        }
                                                        
            
            #line default
            #line hidden
            
            #line 159 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                               

            
            #line default
            #line hidden
WriteLiteral(@"


                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
");

            
            #line 177 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <script>\r\n\r\n    var countDownDate = new Date(\"");

            
            #line 180 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                             Write(item.SessionDate);

            
            #line default
            #line hidden
WriteLiteral("\").getTime();\r\n\r\n\r\n\r\n        </script>\r\n");

            
            #line 185 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n");

            
            #line 187 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
    
            
            #line default
            #line hidden
            
            #line 187 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
      
        foreach(var item in Model)
        {



            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(@"
     function LatestSessionCountDown(key, date, duration)
            {
                // Get today's date and time
                var now = new Date().getTime();

                // Find the distance between now and the count down date
                var distance = new Date(date).getTime() - now;

                // Time calculations for days, hours, minutes and seconds
                var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                var seconds = Math.floor((distance % (1000 * 60)) / 1000);



                // If the count down is over, write some text
                if (distance < 0)
                {
                   // clearInterval(x);
                    //$(""#latestSessionCountDownContainer"").hide();
                    //document.getElementById(""latestSessionSpanElementId"").innerHTML = ""EXPIRED"";
                    //document.getElementById(""latestSessionCountDownContainer"").innerHTML = "" "";
                    //$('#latestSessionCountDownContainer_' + ");

            
            #line 216 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                         Write(item.SynchronousSessionKey);

            
            #line default
            #line hidden
WriteLiteral(@").empty();
                    console.log('before get lastest session');



                }
                else
                {

                    console.log('first date: ' + countDownDate);
                    console.log('first date: ' + hours);
                    var displayMsg = days + ""d "" + hours + ""h "" + minutes + ""m "" + seconds + ""s "" + """);

            
            #line 227 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Remaining")));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                    if (days == 0) {\r\n                        displayMsg = ho" +
"urs + \"h \" + minutes + \"m \" + seconds + \"s \" + \"");

            
            #line 229 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Remaining")));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                    }\r\n\r\n                    if (hours == 0 && days == 0) {\r\n" +
"                        displayMsg = minutes + \"m \" + seconds + \"s \" + \"");

            
            #line 233 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                   Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Remaining")));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                    }\r\n\r\n                    if (minutes == 0 && hours == 0 )" +
" {\r\n                        displayMsg = seconds + \"s \" + \"");

            
            #line 237 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Remaining")));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                    }\r\n\r\n                    // Output the result in an eleme" +
"nt with");

WriteLiteral(" id=\"demo\"");

WriteLiteral("\r\n                    document.getElementById(\"latestSessionSpanElementId_\" + key" +
").innerHTML = displayMsg;\r\n\r\n                }\r\n\r\n            }\r\n\r\n     console." +
"log(\'before get lastest session\');\r\n            LatestSessionCountDown(\'");

            
            #line 248 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                               Write(item.SynchronousSessionKey);

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 248 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                              Write(item.MeetingDuration);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n            // Update the count down every 1 second\r\n            x = setInte" +
"rval(function () {\r\n                LatestSessionCountDown(\'");

            
            #line 251 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                   Write(item.SynchronousSessionKey);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 251 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                 Write(item.SessionDate);

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 251 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
                                                                                     Write(item.MeetingDuration);

            
            #line default
            #line hidden
WriteLiteral(");\r\n            }, 1000);\r\n    ");

WriteLiteral("\r\n");

            
            #line 254 "..\..\Views\PresentialSessions\_PresentialSessionsGrid.cshtml"
            }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </script>\r\n</div>\r\n\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
