#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PresentialSessions/_PresentialUserCard.cshtml")]
    public partial class _Views_PresentialSessions__PresentialUserCard_cshtml : System.Web.Mvc.WebViewPage<RLI.EntityFramework.EDM.Student>
    {
        public _Views_PresentialSessions__PresentialUserCard_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"col-md-7 col-lg-5 col-xl-4 col-10\"");

WriteLiteral(">\r\n    <article");

WriteLiteral(" class=\"post-post-grid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"m-portlet m-portlet--full-height \"");

WriteLiteral(" style=\"margin:0\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"m-portlet__head\"");

WriteLiteral(" style=\"height:100%\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"m-portlet__body row\"");

WriteLiteral(" style=\"padding:25px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-widget3\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"m-widget3__item\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"m-widget3__header\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"m-widget3__user-img usericon\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"far fa-3x fa-user-circle\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"m-widget3__info\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"userflname\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 15 "..\..\Views\PresentialSessions\_PresentialUserCard.cshtml"
                                   Write(Model.FirstName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 15 "..\..\Views\PresentialSessions\_PresentialUserCard.cshtml"
                                                    Write(Model.LastName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </span>\r\n                                  " +
"  <br>\r\n                                    <span");

WriteLiteral(" class=\"middlename\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 19 "..\..\Views\PresentialSessions\_PresentialUserCard.cshtml"
                                   Write(Model.MiddleName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </span>\r\n                                </" +
"div>\r\n                            </div>\r\n                        </div>\r\n      " +
"              </div>\r\n                </div>\r\n            </div>\r\n            <d" +
"iv");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"height:30px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xl-8 col-6\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"col-xl-4 col-6\"");

WriteLiteral(" style=\"padding-bottom:10px;\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </article>\r\n</" +
"div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
