#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 3 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PresentialSessions/_PresentialSessionAudience.cshtml")]
    public partial class _Views_PresentialSessions__PresentialSessionAudience_cshtml : System.Web.Mvc.WebViewPage<RLI.WebApplication.Models.PresentialSessionsAudienceViewModel>
    {
        public _Views_PresentialSessions__PresentialSessionAudience_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    .col-form-label {\r\n        margin-top: 7px;\r\n    }\r\n</style>\r\n\r\n" +
"");

            
            #line 14 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
 using (Html.BeginForm("SessionAudience", "PresentialSessions", FormMethod.Post, new { @class = "m-form m-form--label-align-left", @id = "sessionAudienceForm", role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"m-form__heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"font-weight-bold\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSessionAudience")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </h3>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"m-form__content\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary\"");

WriteLiteral("> ");

            
            #line 27 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                            Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSelectSchool")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                  string school = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                <span>\r\n                    <select");

WriteLiteral(" id=\"SchoolsDropDown\"");

WriteLiteral(" class=\"select-field form-control\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                    </select>\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
               Write(Html.HiddenFor(model => model.SchoolKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"m-form__help m--margin-left-30\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateStartBySelectingSchool")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
           Write(Html.ValidationMessageFor(model => model.SchoolKey, school, new { @class = "text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSelectGrade")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 42 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                  string grade = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                <span>\r\n                    <select");

WriteLiteral(" id=\"GradesDropDown\"");

WriteLiteral(" class=\"select-field form-control\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                    </select>\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
               Write(Html.HiddenFor(model => model.GradeKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"m-form__help m--margin-left-30\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageThenSelectTheGrade")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n");

WriteLiteral("                ");

            
            #line 51 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
           Write(Html.ValidationMessageFor(model => model.GradeKey, grade, new { @class = "text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSelectSubject")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 57 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                  string subject = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateFeildRequired1")).ToString(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                <select");

WriteLiteral(" id=\"SubjectsDropDown\"");

WriteLiteral(" class=\"select-field form-control\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                </select>\r\n");

WriteLiteral("                ");

            
            #line 60 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
           Write(Html.HiddenFor(model => model.SubjectKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" class=\"m-form__help m--margin-left-30\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateAndFinallyTheSubject")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                ");

            
            #line 62 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
           Write(Html.ValidationMessageFor(model => model.SubjectKey, subject, new { @class = "text-danger m--margin-left-20 m--margin-top-5", @style = "display:block;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary\"");

WriteLiteral(">Curriculum Grade</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n\r\n                <span>\r\n                    <select");

WriteLiteral(" id=\"DropDownofCurricculumGrade\"");

WriteLiteral(" class=\"select-field form-control\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                    </select>\r\n");

WriteLiteral("                    ");

            
            #line 73 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
               Write(Html.HiddenFor(model => model.CurricculumGradeKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"m-form__help m--margin-left-30\"");

WriteLiteral(">Select Grade</span>\r\n            </div>\r\n        </div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary\"");

WriteLiteral("> ");

            
            #line 81 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                            Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateSelectChapter")));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n\r\n                <span>\r\n                    <select");

WriteLiteral(" id=\"topicDropDown\"");

WriteLiteral(" class=\"select-field form-control\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                    </select>\r\n");

WriteLiteral("                    ");

            
            #line 87 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
               Write(Html.HiddenFor(model => model.ChapterKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"m-form__help m--margin-left-30\"");

WriteLiteral(">");

            
            #line 89 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "SynchronousSessionsPageCreateStartBySelectingChapter")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group m-form__group row\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"col-lg-3 col-form-label text-primary\"");

WriteLiteral(">Topic</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n\r\n                <span>\r\n                    <select");

WriteLiteral(" id=\"DropDownoftopcis\"");

WriteLiteral(" class=\"select-field form-control\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                    </select>\r\n");

WriteLiteral("                    ");

            
            #line 100 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
               Write(Html.HiddenFor(model => model.TopicKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"m-form__help m--margin-left-30\"");

WriteLiteral(">Select Topic</span>\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 107 "..\..\Views\PresentialSessions\_PresentialSessionAudience.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
