#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Views\Assignments\Index.cshtml"
    using System.Web.Http;
    
    #line default
    #line hidden
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 5 "..\..\Views\Assignments\Index.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Assignments\Index.cshtml"
    using RLI.Common.DataObjects;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Assignments\Index.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Assignments/Index.cshtml")]
    public partial class _Views_Assignments_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CleverOwl.WebApplication.Models.AssignmentCardViewModel>>
    {
        public _Views_Assignments_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Assignments\Index.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;
    //ViewBag.Title = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageAssignments"));
    ViewBag.Title = Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageCreateAssignments"));
    bool iscoordinator = false;
    if ((User.IsInRole("ContentManager") || User.IsInRole("Coordinator") || User.IsInRole("HeadOfDepartment") || User.IsInRole("SchoolPrincipal") || User.IsInRole("SeniorCoordinator")) && ViewBag.CurrentUser.Id != User.Identity.GetUserId())
    {
        iscoordinator = true;
    }

            
            #line default
            #line hidden
WriteLiteral(@"

<style>
    .select2-results {
        padding: 15% !important;
    }

    svg {
        height: 50px;
    }

    .page-banner {
        margin-top: 100px;
        height: fit-content;
        margin-bottom: 30px;
        background-color: #ffffff;
    }



    .page-body {
        padding: 0;
        margin-bottom: 50px;
    }

    .grid-card {
        box-shadow: rgb(99 99 99 / 20%) 0px 2px 8px 0px;
        border-radius: 25px;
        padding: 40px;
        background: linear-gradient( to left, rgb(115 110 197 / 80%) 0%, rgb(68 60 182) 100% ) left bottom #ffffff no-repeat;
        background-size: 100% 18px;
    }

    .grid-card-head-title {
        margin-top: 20px;
    }

    .grid-card-head-datetime {
        margin-top: 20px;
    }

    .grid-card-body {
        margin-top: 25px;
        font-weight: 100;
    }

    .grid-card-footer {
        margin-top: 50px;
        margin-bottom: -10px;
    }

    .table-row {
        display: table-row;
        height: auto;
    }

    .table-cell1 {
        border: none;
        display: table-cell;
        padding: 2px;
        width: 80%
    }

    .table-cell2 {
        border: none;
        display: table-cell;
        padding: 2px;
    }

    video {
        max-width: 398px;
        max-height: 130px;
    }



    .select2-selection__clear {
        padding-top: 8px !important;
    }

    ");

WriteLiteral("@media(min-width: 992px) and (max-width:1024px) {\r\n        .RenderBody {\r\n       " +
"     max-width: 100%;\r\n            padding-right: 15%;\r\n            padding-left" +
": 15%;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral(@"@media (max-width:522px) {
        #select2-recordsDropdown-container {
            position: absolute;
            right: 18%;
        }
    }

    .coordinator {
        pointer-events: none;
        opacity: 0.5;
        cursor: not-allowed;
        filter: grayscale(100%);
    }
</style>

<section");

WriteLiteral(" class=\"page-banner\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"page-title-wrapper\"");

WriteLiteral(">\r\n            <div>\r\n                <ul");

WriteLiteral(" class=\"bradcurmed\"");

WriteLiteral(">\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2927), Tuple.Create("\"", 2966)
            
            #line 124 "..\..\Views\Assignments\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2934), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Dashboard")
            
            #line default
            #line hidden
, 2934), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 124 "..\..\Views\Assignments\Index.cshtml"
                                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageWall")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3103), Tuple.Create("\"", 3144)
            
            #line 125 "..\..\Views\Assignments\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3110), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Assignments")
            
            #line default
            #line hidden
, 3110), false)
);

WriteLiteral(" rel=\"noopener noreferrer\"");

WriteLiteral(">");

            
            #line 125 "..\..\Views\Assignments\Index.cshtml"
                                                                                          Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageAssignments001")));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                </ul>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row m--margin-top-20-desktop\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-1 m-auto m--hidden-tablet m--hidden-mobile\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 130 "..\..\Views\Assignments\Index.cshtml"
               Write(Html.Partial("~/Views/SharedSvgs/_AssignmentsIcon.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-5 col-12 m-auto\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("> ");

            
            #line 133 "..\..\Views\Assignments\Index.cshtml"
                                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageAssignments001")));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-3  m-auto\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-3 col-12 m-auto\"");

WriteLiteral(">\r\n");

            
            #line 138 "..\..\Views\Assignments\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Assignments\Index.cshtml"
                     if (Model != null && Model.Count() != 0)
                    {
                        if (RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name == "Teacher")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <button");

WriteLiteral(" id=\"createButton\"");

WriteLiteral(" type=\"button\"");

WriteAttribute("class", Tuple.Create(" class=\"", 4183), Tuple.Create("\"", 4416)
, Tuple.Create(Tuple.Create("", 4191), Tuple.Create("btn", 4191), true)
, Tuple.Create(Tuple.Create(" ", 4194), Tuple.Create("m-btn--pill", 4195), true)
, Tuple.Create(Tuple.Create(" ", 4206), Tuple.Create("m-btn", 4207), true)
, Tuple.Create(Tuple.Create(" ", 4212), Tuple.Create("m-btn--gradient-from-primary", 4213), true)
, Tuple.Create(Tuple.Create(" ", 4241), Tuple.Create("m-btn--gradient-to-info", 4242), true)
, Tuple.Create(Tuple.Create(" ", 4265), Tuple.Create("pull-right", 4266), true)
, Tuple.Create(Tuple.Create(" ", 4276), Tuple.Create("m--padding-top-15", 4277), true)
, Tuple.Create(Tuple.Create(" ", 4294), Tuple.Create("m--padding-bottom-15", 4295), true)
, Tuple.Create(Tuple.Create(" ", 4315), Tuple.Create("m--padding-left-20", 4316), true)
, Tuple.Create(Tuple.Create(" ", 4334), Tuple.Create("m--padding-right-20", 4335), true)
, Tuple.Create(Tuple.Create(" ", 4354), Tuple.Create("w-100-mobile", 4355), true)
, Tuple.Create(Tuple.Create(" ", 4367), Tuple.Create("pull-right", 4368), true)
            
            #line 142 "..\..\Views\Assignments\Index.cshtml"
                                                                                                                                                                                       , Tuple.Create(Tuple.Create(" ", 4378), Tuple.Create<System.Object, System.Int32>(iscoordinator ? "coordinator" : ""
            
            #line default
            #line hidden
, 4379), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-plus m--padding-right-5\"");

WriteLiteral("></i>\r\n                                <span>\r\n");

WriteLiteral("                                    ");

            
            #line 145 "..\..\Views\Assignments\Index.cshtml"
                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageCreateAssignment001")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </span>\r\n                            </button>\r" +
"\n");

            
            #line 148 "..\..\Views\Assignments\Index.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

            
            #line 155 "..\..\Views\Assignments\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 155 "..\..\Views\Assignments\Index.cshtml"
         if (Model != null && Model.Count() != 0)
        {


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"row mt-4\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-9 pr-0\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-input-icon m-input-icon--left m-input-icon--right\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"searchInput\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control searchInputAssignSync\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 5200), Tuple.Create("\"", 5291)
            
            #line 162 "..\..\Views\Assignments\Index.cshtml"
                                    , Tuple.Create(Tuple.Create("", 5214), Tuple.Create<System.Object, System.Int32>(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageSearch..."))
            
            #line default
            #line hidden
, 5214), false)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"m-input-icon__icon m-input-icon__icon--right mr-3\"");

WriteLiteral("><span><i");

WriteLiteral(" class=\"fas fa-search\"");

WriteLiteral("></i></span></span>\r\n                    </div>\r\n                </div>\r\n\r\n      " +
"          <div");

WriteLiteral(" class=\"col-3 pl-1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"m-input-icon m-input-icon--left m-input-icon--right records-control-widge" +
"t\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n                        <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"recordsDropdown\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" selected=\"\"");

WriteLiteral(">10</option>\r\n                            <option>20</option>\r\n                  " +
"          <option>50</option>\r\n                        </select>\r\n              " +
"          ");

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 180 "..\..\Views\Assignments\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 180 "..\..\Views\Assignments\Index.cshtml"
                 if (RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name != "Student")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-12 m--margin-top-5-mobile\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 183 "..\..\Views\Assignments\Index.cshtml"
                   Write(Html.DropDownList("GradesDropDown", (SelectList)ViewBag.Grades, "Grades", htmlAttributes: new { @class = "form-control", @id = "GradeDropDown", @style = "width:100%;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 185 "..\..\Views\Assignments\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-12 m--margin-top-5-mobile\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 188 "..\..\Views\Assignments\Index.cshtml"
               Write(Html.DropDownList("SubjectDropDown", (SelectList)ViewBag.Subjects, "Subjects", htmlAttributes: new { @class = "form-control", @id = "SubjectDropDown", @style = "width:100%;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-12 m--margin-top-5-mobile\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 191 "..\..\Views\Assignments\Index.cshtml"
               Write(Html.DropDownList("DueDates", (SelectList)ViewBag.DueDates, "DueDates", htmlAttributes: new { @class = "form-control", @id = "DueDatesDropDown", @style = "width:100%;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

            
            #line 194 "..\..\Views\Assignments\Index.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</section>\r\n\r\n<div");

WriteLiteral(" class=\"row mt-5\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"page-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"assignmentDiv\"");

WriteLiteral(">\r\n");

            
            #line 208 "..\..\Views\Assignments\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 208 "..\..\Views\Assignments\Index.cshtml"
                     if (Model == null || Model.Count() == 0)
                    {
                        if (RLI.Common.Managers.UserManager.GetUserRole(ViewBag.CurrentUser.Id).Name == "Teacher")
                        {
                            
            
            #line default
            #line hidden
            
            #line 212 "..\..\Views\Assignments\Index.cshtml"
                       Write(Html.Partial("_EmptySlateContainer", new ViewDataDictionary {
                            { "title", "Hey hey!" },
                            { "subTitle",Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Youdontseemtohaveanyassignments")).ToString() }
                            , { "description", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Creatinganassignmentwillallowyoutosendassignmentsforstudents")).ToString() }
                            , { "action", true },
                            { "actionBtnId", "createButtonInEmptySlate" },
                            { "actionBtnText", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_CreateAssignment001")).ToString() } }));

            
            #line default
            #line hidden
            
            #line 218 "..\..\Views\Assignments\Index.cshtml"
                                                                                                                                       
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 222 "..\..\Views\Assignments\Index.cshtml"
                       Write(Html.Partial("_EmptySlateContainer", new ViewDataDictionary {
                            { "title", "Hey hey!" },
                            { "subTitle",Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Youdontseemtohaveanyassignments")).ToString() }
                            , { "description", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_Creatinganassignmentwillallowyoutosendassignmentsforstudents")).ToString() }
                            , { "action", false },
                            { "actionBtnId", "createButtonInEmptySlate" },
                            { "actionBtnText", Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_CreateAssignment001")).ToString() } }));

            
            #line default
            #line hidden
            
            #line 228 "..\..\Views\Assignments\Index.cshtml"
                                                                                                                                       
                        }

                        
            
            #line default
            #line hidden
            
            #line 246 "..\..\Views\Assignments\Index.cshtml"
                                    
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\Assignments\Index.cshtml"
                   Write(Html.Partial("_AssignmentCard", Model));

            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\Assignments\Index.cshtml"
                                                               
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</div" +
">\r\n\r\n\r\n");

            
            #line 261 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("DeleteAssignment", "Assignments", FormMethod.Post, new { id = "DeleteAssignmentHidden", @class = "", @style = "display:none;" }))
{

    
            
            #line default
            #line hidden
            
            #line 264 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 264 "..\..\Views\Assignments\Index.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 265 "..\..\Views\Assignments\Index.cshtml"
Write(Html.Hidden("assignmentId", ""));

            
            #line default
            #line hidden
            
            #line 265 "..\..\Views\Assignments\Index.cshtml"
                                    
    
            
            #line default
            #line hidden
            
            #line 266 "..\..\Views\Assignments\Index.cshtml"
Write(Html.Hidden("courseId", ""));

            
            #line default
            #line hidden
            
            #line 266 "..\..\Views\Assignments\Index.cshtml"
                                
    
            
            #line default
            #line hidden
            
            #line 267 "..\..\Views\Assignments\Index.cshtml"
Write(Html.Hidden("courseModule", ""));

            
            #line default
            #line hidden
            
            #line 267 "..\..\Views\Assignments\Index.cshtml"
                                    
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 270 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("RemoveBookmark", "Bookmark", FormMethod.Post, new { id = "RemoveBookmarkAssignmentComponentForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 272 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 272 "..\..\Views\Assignments\Index.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 273 "..\..\Views\Assignments\Index.cshtml"
Write(Html.Hidden("assignment_Key", ""));

            
            #line default
            #line hidden
            
            #line 273 "..\..\Views\Assignments\Index.cshtml"
                                      
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 276 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("BookmarkAssignmentComponent", "Dashboard", FormMethod.Post, new { id = "BookmarkAssignmentComponentForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 278 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 278 "..\..\Views\Assignments\Index.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 279 "..\..\Views\Assignments\Index.cshtml"
Write(Html.Hidden("componentKey", ""));

            
            #line default
            #line hidden
            
            #line 279 "..\..\Views\Assignments\Index.cshtml"
                                    
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 282 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("GetLatestSession", "Dashboard", FormMethod.Post, new { id = "GetLatestSessionForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 284 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 284 "..\..\Views\Assignments\Index.cshtml"
                            
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 287 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("GetUserConversations", "Messages", FormMethod.Post, new { id = "GetUserConversationsForLeftMenu" }))
{
    
            
            #line default
            #line hidden
            
            #line 289 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 289 "..\..\Views\Assignments\Index.cshtml"
                            
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 292 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("GetNewBookmarks", "Bookmark", FormMethod.Post, new { id = "GetNewBookmarksHidden" }))
{
    
            
            #line default
            #line hidden
            
            #line 294 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 294 "..\..\Views\Assignments\Index.cshtml"
                            
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 297 "..\..\Views\Assignments\Index.cshtml"
 using (Html.BeginForm("RefreshWhatsToday", "Dashboard", FormMethod.Post, new { id = "RefreshWhatsTodayHidden" }))
{
    
            
            #line default
            #line hidden
            
            #line 299 "..\..\Views\Assignments\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 299 "..\..\Views\Assignments\Index.cshtml"
                            
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 303 "..\..\Views\Assignments\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 304 "..\..\Views\Assignments\Index.cshtml"
Write(Scripts.Render("~/assets/vendors/select2/dist/js/select2.full.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--Reference the SignalR library. -->\r\n");

WriteLiteral("    ");

            
            #line 307 "..\..\Views\Assignments\Index.cshtml"
Write(Scripts.RenderFormat("<script src='https://" + Request.Url.Host + "/{0}'></script>", "~/Scripts/jquery.signalR-2.4.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--Reference the autogenerated SignalR hub script. -->\r\n");

WriteLiteral("    ");

            
            #line 309 "..\..\Views\Assignments\Index.cshtml"
Write(Scripts.RenderFormat("<script src='https://" + Request.Url.Host + "/{0}'></script>", "~/signalr/hubs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script>\r\n\r\n    var AssignmentsPageSearching = \"");

            
            #line 313 "..\..\Views\Assignments\Index.cshtml"
                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageSearching")));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    var AssignmentsPageResultNotFound = \"");

            
            #line 314 "..\..\Views\Assignments\Index.cshtml"
                                    Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageResultNotFound")));

            
            #line default
            #line hidden
WriteLiteral(@""";

    $(document).ready(function () {
        $('.RenderBody').removeClass('col-md-9');
        $('.BodyParent').find('div').first().addClass('m--hidden-mobile m--hidden-tablet');
            $(""#createButton"").click(function () {
                window.location='");

            
            #line 320 "..\..\Views\Assignments\Index.cshtml"
                            Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            });\r\n\r\n        $(document).on(\"click\",\"#createButtonInEmptySlate\"" +
",function () {\r\n                window.location=\'");

            
            #line 324 "..\..\Views\Assignments\Index.cshtml"
                            Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral(@"';
        });

            $('#recordsDropdown').select2({
                language: {
                    noResults: function () {
                        return AssignmentsPageResultNotFound;
                    },
                    searching: function () {
                        return AssignmentsPageSearching;
                    }
                },
                placeholder: 'Sessions Count',
                minimumResultsForSearch: 10
            });
            $('#GradeDropDown').select2({
                language: {
                    noResults: function () {
                        return AssignmentsPageResultNotFound;
                    },
                    searching: function () {
                        return AssignmentsPageSearching;
                    }
                },
                placeholder: '");

            
            #line 348 "..\..\Views\Assignments\Index.cshtml"
                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageGrade001")));

            
            #line default
            #line hidden
WriteLiteral(@"',
                allowClear: true
            });
            $('#SubjectDropDown').select2({
                language: {
                    noResults: function () {
                        return AssignmentsPageResultNotFound;
                    },
                    searching: function () {
                        return AssignmentsPageSearching;
                    }
                },
                placeholder: '");

            
            #line 360 "..\..\Views\Assignments\Index.cshtml"
                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageSubject001")));

            
            #line default
            #line hidden
WriteLiteral(@"',
                allowClear: true
            });
            $('#DueDatesDropDown').select2({
                language: {
                    noResults: function () {
                        return AssignmentsPageResultNotFound;
                    },
                    searching: function () {
                        return AssignmentsPageSearching;
                    }
                },
                placeholder: '");

            
            #line 372 "..\..\Views\Assignments\Index.cshtml"
                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageType001")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                allowClear: true\r\n            });\r\n\r\n                //$(\'.re" +
"adMoreBtn\').click(function () {\r\n                //    var parent = $(this).pare" +
"nt();\r\n                //    var more = parent.find(\'.more\');\r\n                /" +
"/    var dots = parent.find(\'.dots\');\r\n                //    var lessBtn = paren" +
"t.find(\'.lessBtn\');\r\n                //    more.show();\r\n                //    $" +
"(this).hide();\r\n                //    dots.hide();\r\n                //    lessBt" +
"n.show();\r\n\r\n                //});\r\n                //$(\'.lessBtn\').click(functi" +
"on () {\r\n                //    var parent = $(this).parent().parent();\r\n        " +
"        //    var more = parent.find(\'.more\');\r\n                //    var dots =" +
" parent.find(\'.dots\');\r\n                //    var readMoreBtn = parent.find(\'.re" +
"adMoreBtn\');\r\n                //    more.hide();\r\n                //    $(this)." +
"hide();\r\n                //    dots.show();\r\n                //    readMoreBtn.s" +
"how();\r\n                //});\r\n\r\n\r\n                 $(function () {\r\n           " +
" // Reference the auto-generated proxy for the hub.\r\n            var moodleSigna" +
"lRManager = $.connection.moodleSignalRManager;\r\n            // Create a function" +
" that the hub can call back to display messages.\r\n            moodleSignalRManag" +
"er.client.addNewTimelineDataToPage = function (type, payload) {\r\n               " +
" console.log(\'addNEw\');\r\n                console.log(type);\r\n                con" +
"sole.log(payload);\r\n                GetNewTimelineData(payload);\r\n              " +
"  RefreshBadges();\r\n                clearInterval(x);\r\n                GetLatest" +
"Session();\r\n                RefreshWhatsToday();\r\n            };\r\n\r\n            " +
"moodleSignalRManager.client.addNewMessageToPage = function (type, payload) {\r\n  " +
"              console.log(\'GetUserConversationsForLeftMenu\');\r\n                G" +
"etUserConversationsForLeftMenu();\r\n            };\r\n\r\n            moodleSignalRMa" +
"nager.client.addNewBookmarkDataToPage = function (type, payload) {\r\n            " +
"    console.log(type);\r\n                GetNewBookmarks();\r\n            };\r\n\r\n  " +
"          // Start the connection.\r\n            //$.connection.hub.start().done(" +
"function () {\r\n            //    console.log(\'connection.hub.start()\');\r\n       " +
"     //});\r\n            var count = 0;\r\n            if (count == 0) {\r\n         " +
"       console.log(\'im here\');\r\n               $(\"#newPostsBtn\").hide();\r\n      " +
"          //GetNewTimelineData();\r\n                count++;\r\n            }\r\n\r\n  " +
"      });\r\n\r\n            });\r\n    function Delete(assId, courseId, moduleId) {\r\n" +
"\r\n        swal.fire({\r\n                  \"title\": \"");

            
            #line 442 "..\..\Views\Assignments\Index.cshtml"
                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageDeleteAssignment001")));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                  \"text\": \"");

            
            #line 443 "..\..\Views\Assignments\Index.cshtml"
                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageDeleteAssignmentPromptMsg001")));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                  \"type\": \'warning\',\r\n                  \"confirmButtonClass\":" +
" \"btn m-btn--pill btn-danger\",\r\n                  \"confirmButtonText\":\"");

            
            #line 446 "..\..\Views\Assignments\Index.cshtml"
                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageYes001")));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                  showCancelButton: true,\r\n                  \"cancelButtonCla" +
"ss\": \"btn m-btn--pill btn-metal\",\r\n                  \"cancelButtonText\": \"");

            
            #line 449 "..\..\Views\Assignments\Index.cshtml"
                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentsPageCancel001")));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n        }).then((result) => {\r\n\r\n            console.log(result);\r\n\r\n        " +
"          if (result.value) {\r\n                        mApp.block($(\"#assignment" +
"Div\"));\r\n                        DeleteAssignmentById(assId, courseId, moduleId)" +
";\r\n                  }\r\n                });\r\n\r\n        }\r\n\r\n    function DeleteA" +
"ssignmentById(assId,courseId,moduleId) {\r\n\r\n        $(\"#assignmentId\").val(assId" +
");\r\n        $(\"#courseId\").val(courseId);\r\n        $(\"#courseModule\").val(module" +
"Id);\r\n\r\n            $(\"#DeleteAssignmentHidden\").ajaxSubmit({\r\n                b" +
"eforeSubmit: function () {\r\n                },\r\n                success: functio" +
"n (data) {\r\n                    if (data == 200) {\r\n                        Filt" +
"erAssignment();\r\n                    }\r\n                    },\r\n                " +
"error: function (xhr, status, error) {\r\n                    console.log(\"Error I" +
"n DeleteAssignmentHidden !!!!!!!\");\r\n                }\r\n            });\r\n    }\r\n" +
"\r\n    $(\"#recordsDropdown\").change(function () {\r\n        mApp.block($(\"#assignm" +
"entDiv\"));\r\n        FilterAssignment();\r\n    })\r\n\r\n    $(\"#GradeDropDown\").chang" +
"e(function () {\r\n        mApp.block($(\"#assignmentDiv\"));\r\n        FilterAssignm" +
"ent();\r\n    })\r\n\r\n    $(\"#SubjectDropDown\").change(function () {\r\n        mApp.b" +
"lock($(\"#assignmentDiv\"));\r\n        FilterAssignment();\r\n    })\r\n\r\n    $(\"#DueDa" +
"tesDropDown\").change(function () {\r\n        mApp.block($(\"#assignmentDiv\"));\r\n  " +
"      FilterAssignment();\r\n    })\r\n\r\n    $(\"#searchInput\").keyup(function () {\r\n" +
"        setTimeout(function () {\r\n            mApp.block($(\"#assignmentDiv\"));\r\n" +
"            FilterAssignment();\r\n        }, 1000);\r\n    })\r\n\r\n    //$(\".lessonsL" +
"inkInDescriptionTitle\").remove();\r\n    //$(\".lessonsLinkInDescriptionScorm\").rem" +
"ove();\r\n    //$(\".lessonsLinkInDescription\").remove();\r\n\r\n    function FilterAss" +
"ignment() {\r\n            var search = $(\"#searchInput\").val();\r\n            var " +
"records = $(\"#recordsDropdown option:selected\").val();\r\n            var grade = " +
"$(\"#GradeDropDown option:selected\").val();\r\n            var subject = $(\"#Subjec" +
"tDropDown option:selected\").val();\r\n            var dueDate = $(\"#DueDatesDropDo" +
"wn option:selected\").val();\r\n            $.ajax({\r\n                url: \'");

            
            #line 520 "..\..\Views\Assignments\Index.cshtml"
                 Write(Url.Action("AssignmentsFilter", "Assignments"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \'POST\',\r\n                dataType: \"html\",\r\n           " +
"     data: {\r\n                    query:search,records: records, gradeKey: grade" +
", subjectKey: subject, dueDate: dueDate,\r\n                    __RequestVerificat" +
"ionToken: $(\'");

            
            #line 525 "..\..\Views\Assignments\Index.cshtml"
                                              Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\').val()\r\n                },\r\n                success: function (data) {\r\n\r\n     " +
"               $(\"#assignmentDiv\").empty();\r\n                    $(\"#assignmentD" +
"iv\").html(data);\r\n\r\n                    mApp.unblock($(\"#assignmentDiv\"));\r\n    " +
"                //$(\".lessonsLinkInDescriptionTitle\").remove();\r\n               " +
"     //$(\".lessonsLinkInDescriptionScorm\").remove();\r\n                    //$(\"." +
"lessonsLinkInDescription\").remove();\r\n                }\r\n            });\r\n      " +
"  }\r\n\r\n       $(document).on(\"click\", \".assigmentBookmarkBtn\", function () {\r\n  " +
"          event.preventDefault();\r\n\r\n           console.log(\"assignmentBookmarkB" +
"tn click!!!\");\r\n\r\n            var currentElement = $(this);\r\n            var ass" +
"ignmentKey = $(this).attr(\"data-assignId\");\r\n\r\n            mApp.progress($(this)" +
");\r\n            $(\"#componentKey\").val(assignmentKey);\r\n            $(\"#Bookmark" +
"AssignmentComponentForm\").ajaxSubmit({\r\n                        beforeSubmit: fu" +
"nction () {\r\n                        },\r\n                success: function (data" +
") {\r\n                    mApp.unprogress(currentElement);\r\n\r\n                   " +
" console.log(\"sucess!!!\");\r\n\r\n                    if (data == 200) {\r\n\r\n        " +
"                console.log(\"200!!!\");\r\n\r\n                        currentElement" +
".removeClass(\"assigmentBookmarkBtn\");\r\n                        currentElement.ad" +
"dClass(\"assigmentRemoveBookmarkBtn\");\r\n                        currentElement.ht" +
"ml(\'<i class=\"fa fa-bookmark fa-2x text-primary \"></i>\');\r\n                     " +
"       }\r\n                        },\r\n                        error: function (x" +
"hr, status, error) {\r\n                            mApp.unprogress(currentElement" +
");\r\n                            console.log(\"Error In BookmarkAssignmentComponen" +
"tForm !!!!!!!\");\r\n                        }\r\n                    });\r\n        })" +
"\r\n\r\n         $(document).on(\"click\", \".assigmentRemoveBookmarkBtn\", function () " +
"{\r\n             event.preventDefault();\r\n\r\n             console.log(\"assigmentRe" +
"moveBookmarkBtn click!!!\");\r\n\r\n            var currentElement = $(this);\r\n      " +
"      var assignmentKey = $(this).attr(\"data-assignId\");\r\n\r\n            mApp.pro" +
"gress($(this));\r\n            $(\"#assignment_Key\").val(assignmentKey);\r\n         " +
"   $(\"#RemoveBookmarkAssignmentComponentForm\").ajaxSubmit({\r\n                bef" +
"oreSubmit: function () {\r\n                },\r\n                success: function " +
"(data) {\r\n                    mApp.unprogress(currentElement);\r\n                " +
"    if (data == 200) {\r\n\r\n                        currentElement.removeClass(\"as" +
"sigmentRemoveBookmarkBtn\");\r\n                        currentElement.addClass(\"as" +
"sigmentBookmarkBtn\");\r\n                        currentElement.html(\'<i class=\"fa" +
" fa-bookmark fa-2x text-secondary\"></i>\');\r\n\r\n\r\n                    }\r\n         " +
"       },\r\n                error: function (xhr, status, error) {\r\n             " +
"       mApp.unprogress(currentElement);\r\n                    console.log(\"Error " +
"In RemoveBookmarkAssignmentComponentForm !!!!!!!\");\r\n                }\r\n        " +
"    });\r\n        })\r\n\r\n        function GetNewBookmarks() {\r\n\r\n                $" +
"(\"#GetNewBookmarksHidden\").ajaxSubmit({\r\n                beforeSubmit: function " +
"() {\r\n                },\r\n                success: function (data) {\r\n          " +
"          if (data == \"error\") {\r\n                        swal(\"");

            
            #line 612 "..\..\Views\Assignments\Index.cshtml"
                         Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DashboardPageOpps")));

            
            #line default
            #line hidden
WriteLiteral("\", \"");

            
            #line 612 "..\..\Views\Assignments\Index.cshtml"
                                                                                                   Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DashboardPageErrorOccurPleaseTryAgainLater")));

            
            #line default
            #line hidden
WriteLiteral(@""", ""error"");
                        return;
                    }
                    $('#bookmarksSideMenuContainer').empty();
                    $('#bookmarksSideMenuContainer').append(data);
                },
                error: function (xhr, status, error) {
                    swal(""");

            
            #line 619 "..\..\Views\Assignments\Index.cshtml"
                     Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DashboardPageOpps")));

            
            #line default
            #line hidden
WriteLiteral("\", \"");

            
            #line 619 "..\..\Views\Assignments\Index.cshtml"
                                                                                               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DashboardPageErrorOccurPleaseTryAgainLater")));

            
            #line default
            #line hidden
WriteLiteral("\", \"error\");\r\n                    console.log(\"Error In GetNewBookmarksHidden !!!" +
"!!!!\");\r\n\r\n                }\r\n            });\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
