#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AssignmentsSubmission/_SubmissionFeedback.cshtml")]
    public partial class _Views_AssignmentsSubmission__SubmissionFeedback_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_AssignmentsSubmission__SubmissionFeedback_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" id=\"gradingInfoTable\"");

WriteLiteral(" class=\"mt-5\"");

WriteLiteral(">\r\n    <tr>\r\n        <td>Grade</td>\r\n        <td>75/100</td>\r\n    </tr>\r\n    <tr>" +
"\r\n        <td>Graded on</td>\r\n        <td>1, December 2020</td>\r\n    </tr>\r\n    " +
"<tr>\r\n        <td>Graded by</td>\r\n        <td>Laure Issa</td>\r\n    </tr>\r\n</tabl" +
"e>\r\n");

        }
    }
}
#pragma warning restore 1591
