#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CleverOwl.WebApplication;
    
    #line 4 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
    using RLI.Common.DataObjects;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
    using RLI.Common.Managers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AssignmentsSubmission/_SubmissionAssignment.cshtml")]
    public partial class _Views_AssignmentsSubmission__SubmissionAssignment_cshtml : System.Web.Mvc.WebViewPage<RLI.Common.DataObjects.SubmissionDetailsViewModel>
    {
        public _Views_AssignmentsSubmission__SubmissionAssignment_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
  
    Dictionary<string, string> Locale = ViewBag.Locale;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"submissionsInfo\"");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"submissionInfoTable\"");

WriteLiteral(">\r\n        <tr>\r\n            <td><b>");

            
            #line 12 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageSubmissionStatus")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>");

            
            #line 13 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
           Write(Model.SubmissionStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n        </tr>\r\n        <tr>\r\n            <td><b>");

            
            #line 17 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageGradingStatus")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>");

            
            #line 18 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
           Write(Model.GradingStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>");

            
            #line 21 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageDueDate")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>");

            
            #line 22 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
           Write(Model.DueDate);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n        </tr>\r\n        <tr>\r\n            <td><b>");

            
            #line 26 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageTimeRemaining")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n");

            
            #line 27 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              
                var timeRemaining = Model.TimeRemaining.Value;
                var timeRemainingDays = timeRemaining.Days;
                var timeRemainingHours = timeRemaining.Hours;
                var timeRemainingMinutes = timeRemaining.Minutes;
            
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
             if (timeRemainingDays != 0 || timeRemainingHours != 0 || timeRemainingMinutes != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 35 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
               Write(timeRemainingDays);

            
            #line default
            #line hidden
WriteLiteral(" d ");

            
            #line 35 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                    Write(timeRemainingHours);

            
            #line default
            #line hidden
WriteLiteral(" h ");

            
            #line 35 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                          Write(timeRemainingMinutes);

            
            #line default
            #line hidden
WriteLiteral(" m</td>\r\n");

            
            #line 36 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"m--font-danger\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "_DueDateSubmissionMessage")));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 40 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n                <b>\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
               Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageExtensionDueDate")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </b>\r\n            </td>\r\n");

            
            #line 49 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
             if(Model.ExtensionDueDate != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 51 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
               Write(Model.ExtensionDueDate);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 52 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n\r\n        <tr>\r\n            <td><b>");

            
            #line 56 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageLastModified")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>");

            
            #line 57 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
           Write(Model.LastModified);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n        </tr>\r\n        <tr");

WriteLiteral(" id=\"onlinetextRow\"");

WriteLiteral(">\r\n            <td><b>");

            
            #line 61 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageOnlineText")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>\r\n");

            
            #line 63 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                  
                    string text = "";
                    if (Model.OnlineText != null)
                    {
                        text = Model.OnlineText.Replace("'", "").ToString();


                    }
                
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 72 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
           Write(Html.Raw(text));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" id=\"filesSubmissionsRow\"");

WriteLiteral(">\r\n            <td><b>");

            
            #line 76 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageFilesSubmission")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>\r\n");

            
            #line 78 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                 if (Model.SubmissionFile != null && Model.SubmissionFile.Count() > 0)
                {
                    foreach (var attachment in Model.SubmissionFile)
                    {
                        

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" style=\"display: flex; justify-content:space-between\"");

WriteLiteral(">\r\n                            <div>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3271), Tuple.Create("\"", 3339)
            
            #line 85 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
, Tuple.Create(Tuple.Create("", 3278), Tuple.Create<System.Object, System.Int32>(attachment.fileurl.Replace("webservice", "")
            
            #line default
            #line hidden
, 3278), false)
, Tuple.Create(Tuple.Create("", 3323), Tuple.Create("?forcedownload=1", 3323), true)
);

WriteLiteral(" download=\"download\"");

WriteLiteral(" style=\"word-break:break-word;\"");

WriteLiteral(">");

            
            #line 85 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                                                                      Write(attachment.filename);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 88 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                        
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>");

            
            #line 94 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageSubmissionComments")));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n            <td>\r\n                <div");

WriteLiteral(" id=\"comments\"");

WriteLiteral(">\r\n");

            
            #line 97 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                      
                        int userId = int.Parse(Model.MoodleUserId);
                        var groupedBYCommentsTeacher = Model.getCommentResultModel.comments.Where(c => c.userid != userId).GroupBy(item => item.fullname).Select(group => new { Customer = group.Key, Items = group.ToList() }).ToList();
                        var groupedBYCommentsStudent = Model.getCommentResultModel.comments.Where(c => c.userid == userId).GroupBy(item => item.fullname).Select(group => new { Customer = group.Key, Items = group.ToList() }).ToList();
                        foreach (var content in groupedBYCommentsTeacher)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <h6>");

            
            #line 103 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                           Write(content.Customer);

            
            #line default
            #line hidden
WriteLiteral("</h6>\r\n");

            
            #line 104 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                            foreach (AddCommentResultModel item in content.Items)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <p>");

            
            #line 106 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                              Write(Html.Raw(item.content));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 107 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <h6>");

            
            #line 109 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                       Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageMyComments")));

            
            #line default
            #line hidden
WriteLiteral("</h6>\r\n");

WriteLiteral("                        <div");

WriteLiteral(" id=\"studentCommentsContainer\"");

WriteLiteral(">\r\n");

            
            #line 111 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                             foreach (var content in groupedBYCommentsStudent)
                            {
                                foreach (AddCommentResultModel item in content.Items)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-lg-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 117 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                       Write(Html.Raw(item.content));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"         <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-CommentId=\"");

            
            #line 120 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                  Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"deleteComment\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral("></i></a>\r\n                                        </div>\r\n                      " +
"              </div>\r\n");

            
            #line 123 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 126 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"addComment\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#m_scrollable_modal_comment\"");

WriteLiteral("><u>");

            
            #line 129 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                        Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageAddComment")));

            
            #line default
            #line hidden
WriteLiteral("</u></a>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <div");

WriteLiteral(" class=\"mt-3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row mt-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-3\"");

WriteLiteral(">\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"SubBtns\"");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n");

            
            #line 139 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                
            
            #line default
            #line hidden
            
            #line 139 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                 if (Model.Locked == false)
                {
                    var timeRemaining1 = Model.TimeRemaining.Value;
                    var timeRemainingDays1 = timeRemaining1.Days;
                    var timeRemainingHours1 = timeRemaining1.Hours;
                    var timeRemainingMinutes1 = timeRemaining1.Minutes;
                    var today = DateTime.Now;

                    if ( timeRemainingMinutes1 != 0 || Model.ExtensionDueDate != null)
                    {
                        if (Model.SubmissionStatus == "draft" || Model.SubmissionStatus != "submitted")
                        {


            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" id=\"submitBtn\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(">");

            
            #line 152 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                   Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DataTableNext")));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 153 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"


                        }
                        else if (Model.ExtensionDueDate != null)
                        {
                            if (Model.ExtensionDueDate.Value > today)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"editBtn\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-brand mr-3\"");

WriteLiteral(" style=\"width:100px;\"");

WriteLiteral(">");

            
            #line 160 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                           Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "DataTableNext")));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 161 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"

                            }
                             
                        }

                    }

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-3\"");

WriteLiteral(">\r\n\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" id=\"divOnlineTextHidden\"");

WriteLiteral(" hidden>");

            
            #line 179 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                Write(Model.OnlineText);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" id=\"submissionsSaveEdit\"");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"onlineTextBlock\"");

WriteLiteral(" class=\"col-md-6 col-12 mt-2\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"summernote\"");

WriteLiteral(" class=\"note-icon-summernote\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                ");

            
            #line 185 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
           Write(Html.Raw(Model.OnlineText));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"wordsBlock\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                    <span>");

            
            #line 192 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                     Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageWordsCount")));

            
            #line default
            #line hidden
WriteLiteral(" </span>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" id=\"wordsCurrentNumber\"");

WriteLiteral("></span>\r\n                                  /\r\n                    <span");

WriteLiteral(" id=\"wordsLimit\"");

WriteLiteral("></span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <di" +
"v");

WriteLiteral(" id=\"submissionFilesBlock\"");

WriteLiteral(" class=\"col-md-6 col-12 mt-2\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"dropzone\"");

WriteLiteral(" class=\"m-dropzone dropzone m-dropzone--metal\"");

WriteLiteral(" style=\"height:300px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"m-dropzone__msg dz-message needsclick\"");

WriteLiteral(">\r\n                    <div>\r\n                        <i");

WriteLiteral(" class=\"fa fa-file-upload fa-8x\"");

WriteLiteral(" style=\"margin-bottom:20px;\"");

WriteLiteral("></i>\r\n                    </div>\r\n                    <span");

WriteLiteral(" class=\"m-dropzone__msg-desc\"");

WriteLiteral(">");

            
            #line 207 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                  Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageDragDrop")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"filesUploaded\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 211 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                
            
            #line default
            #line hidden
            
            #line 211 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                  
                    if (Model.SubmissionFile != null)
                    {
                        int i = 0;
                        foreach (var attachment in Model.SubmissionFile)
                        {


            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 9526), Tuple.Create("\"", 9543)
, Tuple.Create(Tuple.Create("", 9531), Tuple.Create("fileIndex_", 9531), true)
            
            #line 218 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
, Tuple.Create(Tuple.Create("", 9541), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 9541), false)
);

WriteLiteral(" class=\"col-12\"");

WriteLiteral(" style=\"margin:10px\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 9759), Tuple.Create("\"", 9827)
            
            #line 221 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
, Tuple.Create(Tuple.Create("", 9766), Tuple.Create<System.Object, System.Int32>(attachment.fileurl.Replace("webservice", "")
            
            #line default
            #line hidden
, 9766), false)
, Tuple.Create(Tuple.Create("", 9811), Tuple.Create("?forcedownload=1", 9811), true)
);

WriteLiteral(" download=\"download\"");

WriteLiteral(" style=\"word-break:break-word;\"");

WriteLiteral(">");

            
            #line 221 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                                                                              Write(attachment.filename);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                    </div>\r\n                               " +
"     <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" class=\"removeFile m--font-danger\"");

WriteLiteral(" data-index=\"");

            
            #line 224 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                    Write(i);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-file-name=\"");

            
            #line 224 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                        Write(attachment.filename);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" style=\"cursor: pointer\"");

WriteLiteral(">");

            
            #line 224 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                                                                                                      Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageRemoveFile")));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                    </div>\r\n                               " +
" </div>\r\n                            </div>\r\n");

            
            #line 228 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                            i++;
                        }
                    }
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"SaveBtns\"");

WriteLiteral(" class=\"mt-5\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n");

            
            #line 236 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
        
            
            #line default
            #line hidden
            
            #line 236 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
         if (Model.Locked == false)
        {
            if ((Model.SubmissionStatus == "draft" || Model.SubmissionStatus != "submitted") && Model.ExtensionDueDate == null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" id=\"saveSubmissionBtn\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(">");

            
            #line 240 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageSave")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

WriteLiteral("                <button");

WriteLiteral(" id=\"saveDraftSubmissionBtn\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(">");

            
            #line 241 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                     Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageSaveDraft")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 242 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            }
            else if (Model.ExtensionDueDate != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" id=\"editSubmissionBtn\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(">");

            
            #line 245 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageSaveChanges")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

WriteLiteral("                <button");

WriteLiteral(" id=\"saveDraftSubmissionBtn\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(">");

            
            #line 246 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                                     Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageSaveDraft")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 247 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" id=\"cancelSubmissionBtn\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(">");

            
            #line 248 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
                                                              Write(Html.Raw(UtilitiesManager.GetFieldLabel(Locale, "AssignmentSubmissionPageCancel")));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 249 "..\..\Views\AssignmentsSubmission\_SubmissionAssignment.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
